### ISSUE TITLE
Broken example tables in Gherkin feature files

### ISSUE THREAD

**Issue by adamlacoste** [hiptest/hiptest-issue-tracker#10]
When I use HipTest Publisher (the SAAS interface, specifically) to download my Gherkin feature files, I will sometimes find that Cucumber.js cannot parse these files because they are malformed.  This happens if cells are left empty in a data table in the web interface.  These cells don't seem to be included in the exported Gherkin, and the table rows therefore end up with a mismatched number of columns.

For instance, in the attached file you can see a data table with empty cells.

<img width="1008" alt="screen shot 2016-06-16 at 11 41 32 am" src="https://cloud.githubusercontent.com/assets/914072/16125056/792c19b4-33b7-11e6-9ce2-1a59d9b4f23e.png">

But in the resulting Gherking feature file, these empty cells are simply missing.

```
    Examples:
      | site_name | page_name | section | subnav_menu | destination | URL | hiptest-uid |
      | chron | local | local | houston | local section | https://www.facebook.com/chroncom |  |
      | timesunion | news | news | capitol | news section |  |
      | sfgate | news | news | bayarea | local section |  |
````

**Comment by vincent-psarga** [comment]
Hi Adam,

The question might seem stupid, but do you still experience this issue ? I was writing a regression test to show the bug and wasn't able to reproduce your issue.
Same thing in the SaaS version of hiptest-publisher.

**Comment by adamlacoste** [comment]
Yes, I still get the same results.  Just 1 empty cell at the end of a row instead of the expected 2.

**Comment by vincent-psarga** [comment]
Damn :/
If your project does not have any critical data, would it be possible for you to invite me on the project so I can try to figure out why the output is not correct for you ?

**Comment by adamlacoste** [comment]
Hi Vincent, I'm working on getting you access but the project admin isn't in the office yet.  I'll get him to grant that to you as soon as possible.  In the mean time, I wanted to add that following the change you made for #12 to optionally exclude UIDs from Scenario names and Examples tables, this is what the table above looks like now:

```
    Examples:
      | site_name | page_name | section | subnav_menu | destination | URL |
      | chron | local | local | houston | local section | https://www.facebook.com/chroncom |
      | timesunion | news | news | capitol | news section |
      | sfgate | news | news | bayarea | local section |
```

As you can see, the rows that had an empty cell (2 & 3) in the HipTest datatable have just 5 cells instead of 6 in the gherkin examples table produced.

**Comment by adamlacoste** [comment]
My administrator has informed me that he has granted access to HipTest support in the **WCM project**.  The scenario I am using as my example here, which has been left alone, is **WCM > SJ_Folder > Sharing > Test Scenario Share - Facebook**.  When I download my specs from the HipTest Publisher SAAS interface, I use the following options:

lang=cucumber-javascript
only=features
with_folders=true
no_uids=true

Hope this helps with reproducing the defect, let me know if I can provide any more information.

**Comment by vincent-psarga** [comment]
Hi Adam,

This should be fixed now. You can even revoke the access to the project :)
I'll leave that issue open until you confirm it works fine for you now :)

**Comment by adamlacoste** [comment]
Looks like it's working now!

```
    Examples:
      | site_name | page_name | section | subnav_menu | destination | URL |
      | chron | local | local | houston | local section | https://www.facebook.com/chroncom |
      | timesunion | news | news | capitol | news section |  |
      | sfgate | news | news | bayarea | local section |  |
```

Thanks Vincent!

**Comment by vincent-psarga** [comment]
You're welcome. Thanks for the feedback :)
