### ISSUE TITLE
Clone Scenarios Or Folders to Other Projects in Your Organisation

### ISSUE THREAD

**Issue by dootrixtester** [hiptest/hiptest-issue-tracker#100]
### Steps to reproduce
1. Select scenario or folder
2. Select to Clone

### Expected behaviour
As well as a drop down to add to another folder in the same project, add a drop down to add to a different project completely and then below that filter the folder 

### Actual behaviour
You only get the option to copy into another folder in the same project

### My configuration
**all browsers:**

**Operating system:**

**Comment by cbliard** [comment]
Hi @dootrixtester,

You are right, from a scenario, you can only clone into another folder in the same project.

Meanwhile, you can clone multiple folders to another project: go to the parent folder, select the subfolder you want to clone and click the Clone button to choose a destination project.

![image](https://user-images.githubusercontent.com/176055/37785961-bc34ebec-2dfb-11e8-82a3-72677bf0da07.png)

The cloned folders will be at the root of the destination project, any elements will be renamed if elements with same name already exist.

That workaround being said, our user interface is cumbersome to use when it comes to cloning. From a folder, you can clone subfolders to another project but not scenarios. From a scenario, you can clone it to another project. This should be harmonized to allow any item to be cloned to any destination project and folder.

**Comment by dootrixtester** [comment]
Hi Christophe

Thank you for your reply, unfortunately I do not have to option to clone to
a different project from the sub folders as I don't have the search bar or
list of projects when I select clone:


I am also a little confused about your last paragraph 'From a folder, you
can clone subfolders to another project but not scenarios. From a scenario,
you can clone it to another project.' These two sentences seem to
contradict each other?  Can you please clarify?

Many thanks

*Regards*

*Tracey Ford*
*Senior Test Analyst*
<http://dootrix.com/>


On Thu, Mar 22, 2018 at 5:09 PM, Christophe Bliard <notifications@github.com

**Comment by dootrixtester** [comment]
![cloning sub-folders](https://user-images.githubusercontent.com/36739904/37822239-d37b8356-2e7d-11e8-91fd-e743a2f4510f.png)

**Comment by cbliard** [comment]
Do you have other projects?

About my last paragraph, I meant that cloning lacks consistency accross pages:

From a folder:

![image](https://user-images.githubusercontent.com/176055/37899145-f27ee242-30ea-11e8-89c1-6c54d750477b.png)

From a scenario:

![image](https://user-images.githubusercontent.com/176055/37899188-1aa40a90-30eb-11e8-957e-e9ccae34975a.png)

**Comment by HoudaDabou** [comment]
Hi @dootrixtester,

So, you may have already noticed but now you can clone one or more scenarios, or one or more sudfolders from one project to another =)
