### ISSUE TITLE
Import Scenario DataTable

### ISSUE THREAD

**Issue by vincentg-kereval** [hiptest/hiptest-issue-tracker#101]
I need to maintain about 150 combination of value on a test Scenario.
I'd like to know if there's a way to import/paste an Excel or CSV table into the Scenario Datatable.

**Comment by FatimaEzzahraIdrissi** [comment]
Hi,

We have an item in our roadmap to [import a datatable as CSV](https://trello.com/c/m9H1jhV3/129-import-and-create-datatable-datasets-from-different-formats). This is not planned yet though. In the meantime you can leverage our [REST API to create datatables and datasets](https://hiptest.github.io/slate/#create-a-dataset) programmatically.

Would that fit your needs?
