### ISSUE TITLE
[Question] Is there any way to filter out some tags when creating test run?

### ISSUE THREAD

**Issue by JustasM11** [hiptest/hiptest-issue-tracker#103]
During test run creation I want to filter out automated test cases marked with special tag. Is there way to do this?

**Comment by vincent-psarga** [comment]
Hi,

Currently this is not something that can be done.
We have plans for updating the filtering capabilities of Hiptest (in a general way, not simply at the test run creation level): https://trello.com/c/sprLqFkk/110-filtering-abilities

Best regards,
Vincent

**Comment by JustasM11** [comment]
Thanks for the answer!
