### ISSUE TITLE
Question: Is there any way to find all test scenarios without tag?

### ISSUE THREAD

**Issue by JustasM11** [hiptest/hiptest-issue-tracker#104]
I want to create metric for automated/not automated tests so I put following tags to all my tests scenarios: "automated: yes" and "automated: no". So I have pie chart metric for automation status. But I missed some test scenarios and I want to found test scenarios without both tags. Is there any way to do this?

**Comment by vincent-psarga** [comment]
Hi,

This is not yet possible with our metrics system. That said, we plan on updating it in order to handle more use cases and the one you describe should be available then.

Best regards,
Vincent

**Comment by JustasM11** [comment]
Thanks for the answer!
