### ISSUE TITLE
Jira no longer showing test run results for linked test scenario

### ISSUE THREAD

**Issue by pennyaNZ** [hiptest/hiptest-issue-tracker#106]
### Steps to reproduce
1. Copy hiptest URL into Jira issue Hiptest URL Link
2. Link Test Scenario URL
3. View current test run results for linked scenario

### Expected behaviour
I should see the linked test run results in Jira 

### Actual behaviour
Only links the test scenario not test results

### My configuration
Chrome Browser - Jira in the cloud

**Operating system:**
Windows 10

**Comment by karamosky** [comment]
Hello @pennyaNZ 
We just released a new update to our plugin, all you need is to update Hiptest to the latest version.
Please let me know if this resolve your issue.

**Comment by pennyaNZ** [comment]
Ho Karamosky,

Thanks for that I am using cloud version of JIra - your plugin is version 1.1.8-AC  How do upgrade without reinstalling - I do want to do this if I lose existing test scenario issue links 

Thanks,
Penny

**Comment by karamosky** [comment]
Hi @pennyaNZ 
I think you are already up to date for the plugin.
Have your Synchronized scenario / test run after linking ?

**Comment by aurelien-reeves** [comment]
Hi @pennyaNZ 
Do you still encounter any issue with the Jira add-on?
