### ISSUE TITLE
Unable to enable Slack integration in a Hiptest project

### ISSUE THREAD

**Issue by aefooteqa** [hiptest/hiptest-issue-tracker#108]
### Steps to reproduce
1. In a project, go to Settings -> Integrations -> Slack and try to activate Slack integration

### Expected behaviour
User should be able to configure a project to integrate with Slack

### Actual behaviour
Error is shown:
OAuth Error: redirect_uri did not match any configured URIs.

Passed URI : https://app.hiptest.com/slack/activate
Allowed URI : https://hiptest.net

### My configuration
**Browser: Chrome**

**Operating system: Windows**

**Comment by karamosky** [comment]
Hello @aefooteqa,
Thank you for reporting this issue.
We are already aware of this issue and have provided a fix.
This should be resolved as soon as Slack team approves the updates.
Regards,
Karam
