### ISSUE TITLE
I don't see my tags name in the folder view

### ISSUE THREAD

**Issue by leandro-romero-olx** [hiptest/hiptest-issue-tracker#109]
### Steps to reproduce
1. Go to Scenarios feature
2. Go to subfolder

### Expected behaviour
Hiptest show the tag name in each scenario in the folder view. 
### Actual behaviour
Hiptest not show the tag name as a previous version in the folder view.

### My configuration
**Browser:**
Chrome

**Operating system:**
Mac

Attach screenshot

![screen shot 2018-04-19 at 15 13 04](https://user-images.githubusercontent.com/30843542/39010483-2dcc2abe-43e5-11e8-8c5c-b9f0ae382893.png)

**Comment by JustasM11** [comment]
Me too suffering :(

**Comment by aurelien-reeves** [comment]
Hi,

Indeed the new UI loose that.

We are working on it to bring it back. Sorry for the inconvenience.

**Comment by PhilipSwiatczak** [comment]
Thank you for logging this, in the absence of combined tag search on Test Run results (in your backlog) seeing the Tags is **vital** to drafting reports. We use standard priority tags like High/Medium/Low and seeing those at list level is key. Thanks again!

**Comment by jracenet** [comment]
Hello there!

You can now show/hide tags associated to your scenarios/subfolders in a folder page:

![capture d ecran 2018-04-26 a 15 24 41](https://user-images.githubusercontent.com/3470258/39308537-010938ec-4966-11e8-8c23-fb2eebda6a0d.png)

Hope it helps :)

**Comment by leandro-romero-olx** [comment]
Nice Job @jracenet !!! And really fast, 

Thanks!!!

Regards 

Leandro
