### ISSUE TITLE
Split scenarios option in HipTest Publisher SAAS broken

### ISSUE THREAD

**Issue by adamlacoste** [hiptest/hiptest-issue-tracker#11]
The option to "Split each scenario in a single file" on the HipTest Publisher SAAS form appears not to work.

<img width="697" alt="screen shot 2016-06-16 at 11 48 16 am" src="https://cloud.githubusercontent.com/assets/914072/16125297/b8bd59a2-33b8-11e6-9945-86bf5aff3ed7.png">

I have attempted to download my features with and without that option checked, and the resulting files are the same either way.

<img width="895" alt="screen shot 2016-06-16 at 11 49 15 am" src="https://cloud.githubusercontent.com/assets/914072/16125336/d769f900-33b8-11e6-9498-65f96fe5020e.png">

The files being delivered are feature files containing several scenarios each.  No scenario splitting appears to be taking place.

**Comment by vincent-psarga** [comment]
Hi,

I'll have a look into that, I think the problem comes from a conflict with the "Create a directory structure" option (which generates the feature file for each last level folder).

**Comment by aurelien-reeves** [comment]
Actually the split scenario option is not available for Gherkin languages.
A fix will be deployed to disable that option for cucumber, specflow, and other gherkin languages.
