### ISSUE TITLE
Not able to properly display big data table even in full screen

### ISSUE THREAD

**Issue by lduchemin** [hiptest/hiptest-issue-tracker#110]
### Steps to reproduce
1. Go to a scenario with a data table with a lot of columns.
2. Open the data table in full screen

### Expected behaviour
User should be able to see all the information in the table and scroll right and left if the table is big.

### Actual behaviour
Text is shortened and replaced by "..." which make it complicated to visualize and edit

### My configuration
**Browser:**
Safari v11.0.2 (but it it not browser specific)

**Operating system:**
MacOS High Sierra 10.13.2

**Comment by aurelien-reeves** [comment]
Hi,

Indeed you spot a bug!
Thank you for your report.

Regards,
Aurélien

**Comment by lduchemin** [comment]
Issue solved thanks :)
