### ISSUE TITLE
Hiptest Test Run and JIRA Traceability Matrix colors don't all match

### ISSUE THREAD

**Issue by Phwop** [hiptest/hiptest-issue-tracker#111]
### Steps to reproduce
1. Given you have linked your project to JIRA (cloud in my case)
2. When you view the Burndown Chart
3. Then your test run result colors should match your JIRA Traceability Matrix report result colors.
* Currently: 
![jiravstestrun](https://user-images.githubusercontent.com/19190315/39130029-23deecf6-46da-11e8-86cd-ea79f7b750cf.png)

### Expected behaviour
I believe your test run result colors should match your JIRA Traceability Matrix report result colors.

### Actual behaviour
Instead the JIRA colors and the Test Run results colors don't match. The Retest, Blocked, Skipped, and Work In Progress colors are mismatched between Hiptest Test Runs and JIRA Plugin Traceability Matrix results.

### My configuration
**Chrome: Version 65.0.3325.181 (Official Build) (64-bit)**

**Operating system:**
macOS Sierra: Version 10.12.4

**Comment by aurelien-reeves** [comment]
Hi,

Thank you for your report! We will fix that, sorry for the inconvenience.

Regards,
Aurélien

**Comment by HoudaDabou** [comment]
Hi @Phwop,

Our team has fixed this issue, thanks again for your bug report.

Regards,
Houda
