### ISSUE TITLE
Synchronizing testrun doesn't always work.

### ISSUE THREAD

**Issue by Arie86401** [hiptest/hiptest-issue-tracker#112]
I have added a new scenario to a folder with 6 existing scenarios.
By default this new scenario was inserted at positon 7 in the list.
I moved the new scenario to position 1.

I have one testrun which includes the original folder with 6 scenarios.
I tried to synchronize the test run, but that's not working.
The new scenario is not added to the existing test run.
Tried synchronisation on different levels (testrun / folder / subfolder).
Non of them works.

I created a new testrun and added a new testrun to a folder with 3 scenarios.
This time not moving the scenario, kept it at default position it was inserted.
Again synchronizing the test run does not work.

 
### Steps to reproduce
1. Add new scenario to list/folder with scenarios
2. Synchronize test run with original folder    
3.

### Expected behaviour
New scenarioshould be added to the test run

### Actual behaviour
Scenario is not added to the existing test run

### My configuration
**Browser:** Chrome (Versie 64.0.3282.167 (Officiële build) (32-bits))

**Operating system:** WindowsServer2008R2 Enterprise

**Comment by aurelien-reeves** [comment]
Hi,

New scenario are not added to test run using the synchronization. To add a new scenario to a test run you have to add it.

From the scenario, use the "Add to test run" action menu:
![image](https://user-images.githubusercontent.com/24386780/39194079-335e952e-47dd-11e8-945f-043c1edfa521.png)

From a test run, use the "Add scenarios" action menu:
![image](https://user-images.githubusercontent.com/24386780/39194138-4c20369e-47dd-11e8-9735-22dd14131fc9.png)

Synchronization is used when you update or delete scenarios, or when you add, update or remove datasets in a scenario.

Regards,
Aurélien
