### ISSUE TITLE
Two scenario's with same name in different folders

### ISSUE THREAD

**Issue by Arie86401** [hiptest/hiptest-issue-tracker#113]
In the scenarios section different folders can be created.
However, it is not possible to create two scenarios with the same name in two different folders.

 
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
Tell us what should happen 

### Actual behaviour
Tell us what happens instead 

### My configuration
**Browser:** 

**Operating system:**

**Comment by aurelien-reeves** [comment]
Hi,

This feature is in our Trello backlog, you can take a look here: https://trello.com/c/WpxSfeYp

Feel free to upvote for it!

Regards,
Aurélien
