### ISSUE TITLE
Tagging in New UI No Longer Showing under a list of Test Scenarios When viewed in Sub Folder

### ISSUE THREAD

**Issue by GraemeBrooke** [hiptest/hiptest-issue-tracker#116]
### Steps to reproduce
1. Add Test Scenarios
2. Add Tags to Scenarios
3. View Test Scenarios as a List in Subfolder

### Expected behaviour
Tags should be visible under each Test Scenario when viewing list of Test Scenarios in a Subfolder (They were before UI Refactor)

### Actual behaviour
Tags are only visible if you actually access an individual Test Scenario
### My configuration
**Browser:**

**Operating system:**

**Comment by aurelien-reeves** [comment]
This issue duplicate that one: https://github.com/hiptest/hiptest-issue-tracker/issues/109
