### ISSUE TITLE
Datatable - not able to move column to the left or to delete column

### ISSUE THREAD

**Issue by willawing** [hiptest/hiptest-issue-tracker#118]
### Steps to reproduce
1.  Go to the Datatable inside a scenario
2.  Add new column in datatable
3.  and find that no longer able to move column to the left or to delete a column

### Expected behaviour
Expects always able to:
- move column to the left
- move column to the right
- delete column 
- add column 

### Actual behaviour
- move column to the left (missing)
- move column to the right (works fine)
- delete column (missing)
- add column  (works fine)

### My configuration
**Browser:**
Chrome
![hiptest datatable - only able to move column to the right](https://user-images.githubusercontent.com/38819231/39400762-c26d50f0-4b04-11e8-843d-edc286323ffd.png)

**Operating system:**

**Comment by severinedarlot** [comment]
Hello,
We did not succeed to reproduce your problem. Could you tell us if the problem remains? If it is the case, what is your system and what is your Chrome version?
Thank you

**Comment by jracenet** [comment]
Hey @willawing 

I close this issue. If you still encounter this bug, feel free to open it again :)
