### ISSUE TITLE
Wrong steps (from another scenario) are displayed when scenario is added to test run

### ISSUE THREAD

**Issue by NatalijaRokina** [hiptest/hiptest-issue-tracker#119]
### Steps to reproduce

1. I created subfolder with user story
2. I created scenarios  for testing
3. I added steps to each scenario 
4. I created test run using option ```<Select a subset of tests>```
5. I chose tests I needed
6. I pressed ```<create>```
7. I start executing the test
8. I can see scenarios' titles from my test case

### Expected behaviour

I can see steps from my scenarios

### Actual behaviour

I can see steps from old scenarios

### My configuration

**Chrome:**

**Win10:**

**Comment by severinedarlot** [comment]
Hello Natalija,

Thank you for your feedback. I don't succeed to reproduce your problem. Could give us more information? Is the problem remain after refreshing the browser? Is it possible to send us screenshot of the problem? Which view is displaying the wrong steps?

Thank you
Regards

**Comment by HoudaDabou** [comment]
Hi @NatalijaRokina,

Do you still have this problem?

Thanks in advance.

Regards,
Houda
