### ISSUE TITLE
Tester role should be able to modify or create test runs

### ISSUE THREAD

**Issue by leandro-chescotta-olx** [hiptest/hiptest-issue-tracker#120]
We are a large team of functional and automation people working together using Hiptest, to manage scenario creation quality, we have only 2 people reviewing changes, and the rest of the team, have the Tester role permissions, but this disables this users for creating, modifying and deleting Test runs.

We need a new role or setting that allows them permission on Test runs but not to change the main project.

**Comment by severinedarlot** [comment]
Hello Leandro,

We are currently working on the capability to add custom roles. 
![selection_103](https://user-images.githubusercontent.com/1829919/39822514-0c682532-53ab-11e8-9003-06012a10251c.png)

But this is a beta feature. If you want I can grant your organization this feature. Just send an email to hello_at_hiptest.com with the name of your organization.

Regards

**Comment by HoudaDabou** [comment]
Hi @leandro-chescotta-olx,

As @severinedarlot said you, if you would like to take advantage of this beta feature, feel free to contact us by email (support@hiptest.com).

Regards,
Houda
