### ISSUE TITLE
Implement a way to review changes before commit

### ISSUE THREAD

**Issue by leandro-chescotta-olx** [hiptest/hiptest-issue-tracker#121]
As we are a large team working on the same project, with people of varying testing seniorities, we need to have a way to apply some sort of review of the changes the users do in the project, so that the changes only apply after a designated user review them.

In a way it could be a code review, applied to the Gherkin, tags, naming, etc.

**Comment by jracenet** [comment]
Hey @leandro-chescotta-olx 
We have integrated this enhancement in our backlog:

https://trello.com/c/cTZQaxhq/436-draft-mode-with-review-for-scenario-edition

I close this issue.
