### ISSUE TITLE
Join tags to improve metrics results

### ISSUE THREAD

**Issue by yael-lorenzo-olx** [hiptest/hiptest-issue-tracker#122]
Currently it is very difficult to manage the metrics comparing tags as we have to segregate a lot the information. 
Example: I have a web project that handles mobile and desktop views. 
Requirement: I would like to see which scenarios are automated, to automate, and to define (to finish). I would like to see this for mobile, desktop and as unique project.
If I want to see all the automated mobile scenarios I have to add a tag @webMobileAutomated instead of using two tags and join them like @webMobile @automated.

Example of current situation

![image](https://user-images.githubusercontent.com/22622247/39818180-ae31abb6-5376-11e8-8e3c-bbade50ae6a4.png)

Example of desired situation:

![image](https://user-images.githubusercontent.com/22622247/39818230-cde1d490-5376-11e8-9f55-c64372b7bc6f.png)

Where the solution might be so simple as @tag1.@tag2.@tag3 as col1, @tag1.@tag5 as col 2

**Comment by jracenet** [comment]
Hey @yael-lorenzo-olx 

We have included your feature request in our backlog:
https://trello.com/c/slHA40to/449-configure-more-precisely-the-charts-data-input

I close this issue.

**Comment by yael-lorenzo-olx** [comment]
Thanks @jracenet I am voting the trello! :)
