### ISSUE TITLE
Getting Error when trying to change default URL for Hiptest 1.2.2 in JIRA 7.6.0

### ISSUE THREAD

**Issue by cah-ronald-adkins** [hiptest/hiptest-issue-tracker#123]
### Steps to reproduce
1.  From within JIRA, select Add-Ons
2.  Select Manage Add-Ons
3.  Select Configure from the HipTest Add-On
4.  Change the default URL to https://app.hiptest.com
5.  SSL Error Pops up:  SSL error! Are you sure this url has a valid certificat? - javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target.

### Expected behaviour
The HipTest add-on should accept the new default URL

### Actual behaviour
Get an SSL error:  SSL error! Are you sure this url has a valid certificat? - javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

### My configuration
**Browser:**
Chrome - Version 66.0.3359.139 (Official Build) (64-bit)
IE - Version 11.2189.14393.0

**Operating system:**
Windows 10 on Client.  JIRA Data Center Server v7.6.0 is running on Linux version 4.9.85-38.58.amzn1.x86_64 (mockbuild@gobi-build-60007) (gcc version 7.2.1 20170915 (Red Hat 7.2.1-2) (GCC) )

**Comment by karamosky** [comment]
Hello @ronald-adkins,
We are currently investigating this issue.
For privacy reasons I have sent a direct email for more debugging materials.
Kind regards,
Karam

**Comment by karamosky** [comment]
Hello @ronald-adkins ,

We strongly believe that you Jira instance is using predefined / imported certificates from the keystore to connect to external services.
We also think that the last Hiptest domain name (hiptest.net) was part of those certs.

To let us understand better this issue, we need some extra debugging info.
Could you please change the Hiptest plugin url to the following values and send us a screen shot of each of them when clicking save button.

1 - https://sha256.badssl.com
2 - https://incomplete-chain.badssl.com
3 - https://untrusted-root.badssl.com

Thank you very much for your time.
Regards,
Karam

**Comment by ronald-adkins** [comment]
Thanks Karam,
  I get the exact same message when trying to save any of those URLs (see screenshot below).  I talked to our server team and they mentioned that CardinalHealth does not provide certificates to 3rd party FQDNs, so I’m not sure how a certificate was added for hiptest.net.  I will try and find out if that cert was part of the keystore we have on our server.

Thanks,

Ron

[cid:image001.png@01D3F991.EB4CF620]



_______________________
[cid:image001.png@01D28E7E.59F7C800]

Ron Adkins
Assurance Management Office (AMO)  – Tools Support
5100 Rings Road Dublin, OH 43017 (South Campus)
614.652.1753 work ● 614.652.2014 fax ● 614.477.1156 mobile

**Comment by ronald-adkins** [comment]
Thanks Christophe,
  I will look into this as our network team doesn’t seem to “want” to create a CA certificate for it.

Thanks,

Ron

_______________________
[cid:image001.png@01D28E7E.59F7C800]

Ron Adkins
Assurance Management Office (AMO)  – Tools Support
5100 Rings Road Dublin, OH 43017 (South Campus)
614.652.1753 work ● 614.652.2014 fax ● 614.477.1156 mobile

**Comment by HoudaDabou** [comment]
Hi @ronald-adkins,

Any update on the creation of CA certificate to solve this issue?

Thanks in advance.

Regards,
Houda
