### ISSUE TITLE
Actionwords no longer have the number of calls displayed

### ISSUE THREAD

**Issue by beth-holmes-schneider** [hiptest/hiptest-issue-tracker#124]
### Steps to reproduce
1. View the actionwords tab within a project
2. Notice that the actionwords no longer have the number of calls displayed

### Expected behaviour
In the previous release, the number of calls was displayed next each actionword in the list

### Actual behaviour
The number of calls of each actionword is no longer visible in this tab

Note: they are available in the suggested steps, but we want to refactor our actionwords database and the info showing in the Actionwords tab will be invaluable to this.

### My configuration
**Browser: Chrome**

**Operating system: Windows 7**
[](url)

**Comment by FatimaEzzahraIdrissi** [comment]
Hello,

The action word calls count is back :) Please refresh your browser to get the update.Thank you for your feedback!

Best Regards,
Fatima

**Comment by beth-holmes-schneider** [comment]
Excellent, thank you!

Kind regards, 
Beth
