### ISSUE TITLE
[API] Adding tags in test snapshots (test of test runs)

### ISSUE THREAD

**Issue by suciolx** [hiptest/hiptest-issue-tracker#125]
the current condition in order to get tags, we need to get the scenario id then search for the tags. The problem happen when we  modify the tags in base scenario, then we are no longer get correct tag anymore (the tags of test snapshot change based on scenario tags). in order to still get the actual tags of test snapshots, could you please add tags information on this endpoint

endpoint : https://app.hiptest.com/api/projects/<project_id>/test_runs/<test_run_id>/test_snapshots

**Comment by FatimaEzzahraIdrissi** [comment]
Hello,

Actually we have a planned Trello card about this endpoint in our public backlog. Please find here the link so you can vote for it: [https://trello.com/c/GMXtoWFP/350-api-get-test-tags](https://trello.com/c/GMXtoWFP/350-api-get-test-tags)

Best regards,
Fatima
