### ISSUE TITLE
Closing Access on A Hiptest Environment

### ISSUE THREAD

**Issue by GraemeBrooke** [hiptest/hiptest-issue-tracker#127]
Good morning
An ex employee previously created a site to experiment in separate to our live Hiptest site whilst he was with us but he has now left the organisation

As he used a company Email Address that is no longer in existence I need to find a way to prevent access being gained, in the unlikely event that should he attempt to do so

Please can you advise best way to close this account

I did email aurlane.pascal last week but have not had a reply?

Many thanks

**Comment by FatimaEzzahraIdrissi** [comment]
Hello,

Please contact us at support@hiptest.com or using the in-app chat from hiptest.com so we can do the necessary.

Best regards,
Fatima
