### ISSUE TITLE
Ability to upload a markdown (ext - .md)  file as an attachment (enhancement request)

### ISSUE THREAD

**Issue by ramaniv** [hiptest/hiptest-issue-tracker#128]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### My configuration
**Browser:**

**Operating system:**

**Comment by FatimaEzzahraIdrissi** [comment]
Hello,

This enhancement has been deployed, so now you can upload a Markdown file as an attachment. Please refresh your browser to get the update.

Best regards,
Fatima

**Comment by ramaniv** [comment]
This is not working as expected. Could you please reopen

**Comment by vincentcapicotto** [comment]
Hi,

I just deployed a fix for this issue, can you test it and tell me if it's ok for you?

Thank you
Vincent

**Comment by ramaniv** [comment]
works now. thanks
