### ISSUE TITLE
Test run window freezes regularly for several seconds

### ISSUE THREAD

**Issue by JustasM11** [hiptest/hiptest-issue-tracker#129]
Test run window freezes regularly for several seconds

### Steps to reproduce
1. Create large test run
2. Execute tests
3. Stay some time on page

### Expected behaviour
No freeze observed

### Actual behaviour
Window and all control freezes
![image](https://user-images.githubusercontent.com/12593214/40360030-5ee8b6ec-5dcd-11e8-8b81-f8522b32190a.png)

### My configuration
**Browser:**
Version 66.0.3359.181 (Official Build) (64-bit)

**Operating system:**
Windows 64

**Comment by HoudaDabou** [comment]
Hi @JustasM11 and @LenaTsuber,

Do you always observe this display instability when running your tests?

Thanks in advance.

Regards,
Houda

**Comment by JustasM11** [comment]
Hello, looks like it is already fixed, please feel free to close it.
