### ISSUE TITLE
Test Run Reset automatically Lost all previous run 

### ISSUE THREAD

**Issue by kailashsg** [hiptest/hiptest-issue-tracker#133]
### Steps to reproduce
1. Multiple people login ( around 15) and work on a single test run 
2. Hiptest interface is very slow and while passing test step hiptest sometimes marks test as skipped
3. End of the day the entire test run has been reset to 0 test run 

### Expected behaviour
Hip test should not reset test run without an admin user 

### Actual behaviour
Test run reset, all previous execution lost 
Hip test should not be slow 
### My configuration
Windows 10 and Mac High sierra - Chrome and IE

**Comment by cbliard** [comment]
After analysis, it looks like the execution cycle was closed by mistake by a user and a new one was opened. Results are still there and they can be viewed by browsing history. You can continue completing your tests in the new execution cycle you just created and we'll find a way to merge both execution cycle together.

**Comment by cbliard** [comment]
Hi @kailashsg,

As the test run results have been restored last Friday, are you ok to close this issue?

**Comment by kailashsg** [comment]
Hi Chistophe,

Yes please close the issue. Thanks for resolving it.

Kailash
