### ISSUE TITLE
Cannot delete scenario folders

### ISSUE THREAD

**Issue by beth-holmes-schneider** [hiptest/hiptest-issue-tracker#134]
### Steps to reproduce
1. Given you are viewing a folder within the scenarios
2. When you click on the 3 dots
3. Then no option appears to delete the folder

### Expected behaviour
There should be a way to delete scenario folders

### Actual behaviour
Currently, I cannot see a way to delete them

### My configuration
**Browser: Chrome**

**Operating system: Windows 7**

**Comment by FatimaEzzahraIdrissi** [comment]
Hello,

Deleting a folder is available from its parent, just navigate to the parent folder, select the folder you want to delete and the delete option will appear in the menu:
![image](https://user-images.githubusercontent.com/22891277/40476189-b47baee4-5f43-11e8-8a91-8657a1861107.png)

Best regards,
Fatima

**Comment by beth-holmes-schneider** [comment]
Thanks! So its just the documentation that needs updating :) https://hiptest.com/docs/organize-your-project/
