### ISSUE TITLE
Infinity% on metrics wheel

### ISSUE THREAD

**Issue by beth-holmes-schneider** [hiptest/hiptest-issue-tracker#136]
Just a minor bug noticed 

### Steps to reproduce
1. Given you are viewing the metrics for a test run
2. When you hover over the wheel
3. Then you see Infinity%

![infinitypercent](https://user-images.githubusercontent.com/29397469/40782227-8a8b9188-64d6-11e8-97eb-746b33c0ca0e.png)

### Expected behaviour
Actual percentages should be shown.

### Actual behaviour
Infinity%

### My configuration
**Browser:** Chrome
**Operating system:** Windows 7

**Comment by FatimaEzzahraIdrissi** [comment]
Hello @beth-holmes-schneider,

Thank you for your feedback! A ticket is opened and the team will do the necessary.

Best regards,

**Comment by cbliard** [comment]
Hello @beth-holmes-schneider,

We have deployed a fix for this. It should be fixed now. Thanks for letting us know.

I'm closing the issue but feel free to reopen it if you notice anything wrong about the fix.
