### ISSUE TITLE
enhancement request - Provide a way to show the Dataset name from data tables in Living document 

### ISSUE THREAD

**Issue by ramaniv** [hiptest/hiptest-issue-tracker#138]
### Steps to reproduce
1. I create a scenario with a data table
2. I document the description of the each row in the **Dataset Name** column 
3. Add this scenario to test run
4. Generate Living document

### Expected behaviour
I want to be able to see the **Dataset Name** which provides the reader with information regarding the scenario Example in the Living document. This will help the reader understand the scenario example better.  

### Actual behaviour
Currently the Dataset name is not showing in the document.

### My configuration
**Browser:**

**Operating system:**

**Comment by vincent-psarga** [comment]
Hi,

This would indeed be a nice to have feature. I've added it for the discussion in our next product meeting.

**Comment by jracenet** [comment]
Hey,

This enhancement has been included in our backlog:
https://trello.com/c/kUuSHfsk/435-display-dataset-name-in-examples

I close this issue.
