### ISSUE TITLE
Metrics Colours

### ISSUE THREAD

**Issue by yael-lorenzo-olx** [hiptest/hiptest-issue-tracker#140]
We would like to be able to select the tag color to show correct metrics.
Here you can see an example.

![image](https://user-images.githubusercontent.com/22622247/41534904-a9c0cbfa-72d6-11e8-980d-19a0087c0908.png)

We are already using the same "color profile"

**Comment by aurelien-reeves** [comment]
Indeed in conjunction with #139 that would be nice.
I submit your feature request to the team :+1:

**Comment by jracenet** [comment]
Hey @yael-lorenzo-olx 
This feature has been integrated in our backlog:
https://trello.com/c/gxNUUSt0/445-choose-colors-for-tags

I close this issue
