### ISSUE TITLE
Support button (Open Chat) is not visible anymore

### ISSUE THREAD

**Issue by sergiybuch** [hiptest/hiptest-issue-tracker#141]
### Steps to reproduce
1. Open Hiptest
2. Right bottom corner was button to open chat with support person : Not visible anymore

### Expected behaviour
Button should be there

### Actual behaviour
No button visible

### My configuration
Chrome/Edge

**Operating system:**
Windows 10 Pro

**Comment by aurelien-reeves** [comment]
Hi,

Outside the trial period, the in-app chat is available for paying Hiptest plans.
Are you part of an organization which registered a plan Lite or Pro? If so please contact us at support@hiptest.com.

Regards,
Aurélien

**Comment by aurelien-reeves** [comment]
Hi,

We've just release a new version of Hiptest that should indeed fix an issue with the in-app chat. It was indeed missing in some cases.

Regards,
Aurélien
