### ISSUE TITLE
Attachements not visible in the scenario during Test Run

### ISSUE THREAD

**Issue by pciganik** [hiptest/hiptest-issue-tracker#143]
### Steps to reproduce
1. Add attachements for the Scenario
2. Add Scenario to Test Run
3. Resume test
4. I can't see attachements assignet to Scenario 

### Expected behaviour
All atachements assigned to Scenrario will be downloaded or accessible from the Test Run

### Actual behaviour
All atachements assigned to Scenrario are not visible, and accessible from the Test Run

### My configuration
**Browser:**
Chrome 67.0.3396.87
**Operating system:**
Windows 10

**Comment by aurelien-reeves** [comment]
Indeed that would be useful.

Actually this is already in our backlog as you can see here: https://trello.com/c/lAR9Tlkv
Feel free to upvote for it!

Regards,
Aurélien
