### ISSUE TITLE
Parameter Values not visible in executed Scenario

### ISSUE THREAD

**Issue by pciganik** [hiptest/hiptest-issue-tracker#144]
### Steps to reproduce
1. Define action word with parameters:
   actionword 'Provést transakci' (transactionType = "PRODEJ", cardType, __free_text = "") do
     step {action: "Na POS terminálu provedeme transkaci $(transactionType) kartou $(cardType)"}
   end
2. Add action word like a step to Scenario:
   scenario 'Servisní kódy - PRODEJ' do   
      call 'Provést transakci' (transactionType = "PRODEJ", cardType = "0 (SC3_100 - no restrictions, PIN required)")
   end
3. After click on View tests button I see:
   Action   Na POS terminálu provedeme transkaci $(transactionType) kartou $(cardType)
4. Also when I add Scenrario to Test Run and Resume test, I see:
   1   Action   Na POS terminálu provedeme transkaci $(transactionType) kartou $(cardType)

### Expected behaviour
I would like to see: Na POS terminálu provedeme transkaci Prodej kartou XYZ

### Actual behaviour
I have defined Action word with parameters. I added them as a Test Step in the Scenario and assigned values to parameters. When I click on View tests button, or add Scenario to Test Run I can't see parameter values. 

### My configuration
**Browser:**
Chrome
**Operating system:**
Windows 10

**Comment by aurelien-reeves** [comment]
Hi,

You must use ${} instead of $() to use your parameters.

Your actionword definition should looks like:

```
actionword 'Provést transakci' (transactionType = "PRODEJ", cardType, __free_text = "") do
  step {action: "Na POS terminálu provedeme transkaci ${transactionType} kartou ${cardType}"}
end
```
