### ISSUE TITLE
Possibility to define Time Estimate for Scenario

### ISSUE THREAD

**Issue by pciganik** [hiptest/hiptest-issue-tracker#145]
It would be nice to have possibility define estimate time for the Scenario and show the sum of this estimates cross all scenarios assigned to Test Run.

**Comment by aurelien-reeves** [comment]
Hi,

This is already in our backlog as you can see here: https://trello.com/c/fLRA0Aln

Feel free to upvote for it, and other features you would like to see be part of Hiptest :)

Regards,
Aurélien
