### ISSUE TITLE
Feature Request: Create new Test Run based on Previous Test Run test status

### ISSUE THREAD

**Issue by Phwop** [hiptest/hiptest-issue-tracker#147]
As a user I would like to be able to create new test runs that are a subset of an executed test run based on the test statuses of the previously executed test run. Currently it seems difficult to create a test run that consists of, for example, only the tests that Failed in a previous test run. If I could either re-run an existing Test Run with the option to retain all Pass/Skip/etc statuses on tests OR I could create a new test run that included only the tests with Fail/Retest/etc statuses, it would be very convenient.

Currently I feel I have to either re-run a whole test run and double-check against my previous results OR I have to open the results of an old test run on one page and the Create Test Run feature on another page and comb through my results to get a test run that targets only the problem areas in my app.

**Comment by aurelien-reeves** [comment]
Hi,

This is already part of our backlog. You can take a look at it here: https://trello.com/c/BourXriM

Feel free to upvote for the feature! :)
