### ISSUE TITLE
Feature request: Step argument data tables

### ISSUE THREAD

**Issue by adamlacoste** [hiptest/hiptest-issue-tracker#15]
Currently, HipTest supports scenario outline data tables, but not the Gherkin feature of step argument data tables (https://cucumber.io/docs/reference#data-tables).  It would be highly useful to be able to define a data table for a particular step, e.g. to describe a set of fields that need to be filled out.  Right now there is no option but to stack a bunch of repetitive steps with minor variations in data.

**Comment by vincent-psarga** [comment]
Hi Adam,

We plan to add that in the product :) Enabling docstrings (or pystrings) was the first step toward having the possibility to set datatables at the action word level.

Best regards,
Vincent

**Comment by adamlacoste** [comment]
Great to hear it, please keep us posted.

**Comment by aurelien-reeves** [comment]
Hi Adam,

Step datatables have been deployed some weeks ago :)

Regards,
Aurélien
