### ISSUE TITLE
Automation integration - No option displayed for ‘Java (JUnit / TestNg)’

### ISSUE THREAD

**Issue by fjanes-at-amadeus-dot-com** [hiptest/hiptest-issue-tracker#151]
### Steps to reproduce
1. See:   https://github.com/hiptest/hiptest-publisher/#hiptest-publisher

### Expected behaviour
On "Automation" Page,, option should be displayed for 'Java (JUnit / TestNg)’

### Actual behaviour
Option is NOT displayed for 'Java (JUnit / TestNg)’

### My configuration
Firefox 61.0.1  64bit

**Operating system:**
Windows 7 Enterprise

**Comment by cbliard** [comment]
Hi,

Here is an annotated screenshot of the Automation page from app.hiptest.com

![image](https://user-images.githubusercontent.com/176055/42555510-d2bd4d8e-84e8-11e8-993b-47d1534854cc.png)

The options to generate Java JUnit and Java TestNG exports are present. Can you share a screenshot showing the missing options?

**Comment by fjanes-at-amadeus-dot-com** [comment]
This is what we have:

https://hiptest-digitalame.amaext.tools/projects/13/exports

![image](https://user-images.githubusercontent.com/28764519/42577495-75786c44-84f2-11e8-85f9-f7adfc9064d4.png)

**Comment by cbliard** [comment]
Thanks for the screenshot, I understand the issue now. I'll continue this conversation by email.

**Comment by cbliard** [comment]
Email sent. Have you received it?
