### ISSUE TITLE
Newly created scenarios aren't visible after re-ordering a scenario

### ISSUE THREAD

**Issue by Phwop** [hiptest/hiptest-issue-tracker#152]
### Steps to reproduce
1. Given you have multiple scenarios in a folder
2. When you rearrange one or more of those scenarios
3. And you attempt to add a new scenario to that folder
4. Then you should see the new scenario in that folder's scenario list immediately
-- Currently the new scenario is not being displayed until the screen is refreshed.

### Expected behaviour
Re-ordering a folder's scenarios shouldn't affect how scenarios are added to that folder.

### Actual behaviour
Re-ordering a folder puts the scenario list into a state where new scenarios will not be displayed until the page is refreshed.

### My configuration
**Browser:**
Chrome Version 67.0.3396.99
**Operating system:**
MacOS Sierra 10.12.4 (16E195)
MacBook Pro 2016

**Comment by TimotheeVille** [comment]
Hi,

Thank you for your report! We will fix that, sorry for the inconvenience.

Regards,
Timothée.

**Comment by FatimaEzzahraIdrissi** [comment]
Hello,

Happy to announce that the bug has been fixed. Please refresh your browser to get the update!

Best regards,
Fatima
