### ISSUE TITLE
Authorisation Error Message when selecting Bitbucket Repository in creating Living Documentation

### ISSUE THREAD

**Issue by lee-alderdice** [hiptest/hiptest-issue-tracker#155]
I am creating Living Documentation against a Git repository hosted in Bitbucket but on selecting the repository (clicking on the link) I am getting an error message stating "It seems that Hiptest is no longer authorized to query your repositories.

Steps:

1. Add new
2. Select Git repository
3. Connect to Bitbucket and authenticate
4. Personal and Organizational repositories Listed
5. Click on repository name
6. Receive error message.

![image](https://user-images.githubusercontent.com/11538808/44393843-a2e79f00-a52d-11e8-8c7e-907cbecc939c.png)

**Comment by aurelien-reeves** [comment]
Thank you for the report, we will take a look on that.
Sorry for the inconvenience

**Comment by karamosky** [comment]
Hello @lee-alderdice,
We have deployed a fix for the issue, can you confirm if it's working on your side?
Many thanks,
Karam

**Comment by lee-alderdice** [comment]
Hello @karamosky,

That is working now.  Many thanks for a quick resolution.

Lee
