### ISSUE TITLE
[API] Unable to add datasets to a Scenario using Hiptest REST APIs

### ISSUE THREAD

**Issue by karthikprakash** [hiptest/hiptest-issue-tracker#157]
UseCase : Create the datatsets for a Scenario using Hiptest APIs. 
 
### Steps to reproduce
1.  Using a REST client perform a POST request to create the dataset for the Scenario. (Details in the Word Doc)
2. The Response does not return the datasets created and also the UI doesn't reflect the same under the Datatable section in Scenarios (Screenshots in the Word doc)

### Expected behaviour
datasets should be created

### Actual behaviour
dataset is created but the parameters names and values is not updated. 

Refer the document below for sample request payload and the response returned. 

[DataSet_Creation_for_Scenarios.docx](https://github.com/hiptest/hiptest-issue-tracker/files/2370825/DataSet_Creation_for_Scenarios.docx)

Organization: ClearCare
Source Project: ClearCare-Backlog
Destination Project: Clearcare - New

**Comment by TimotheeVille** [comment]
Indeed, this is a bug.

**Comment by TimotheeVille** [comment]
A fix has been deployed! Can you please retry?

**Comment by karthikprakash** [comment]
I created around 42 datasets for a scenario and all worked fine. Refer the below Request and Response.
Request Payload: 
{u'attributes': {u'data': {u'admin': u'Super Admin', u'client_profile_type': u'community_client_with_services2'}, u'name': 'datatset-42'}, u'type': u'datasets', u'id': u'3818054', u'links': {u'self': u'/datasets/3818054'}}
{'data': {'attributes': {'data': {u'admin': u'Super Admin', u'client_profile_type': u'community_client_with_services2'}, 'name': 'datatset-42'}}}

Response: 
(201, u'{"data":{"type":"datasets","id":"4032888","attributes":{"name":"datatset-42","data":{"admin":"Super Admin","client_profile_type":"community_client_with_services2"}},"links":{"self":"/datasets/4032888"}},"included":[]}')

Refer below for Screenshot of the UI Dataset Table.
![image](https://user-images.githubusercontent.com/25166558/45550222-e04afe00-b847-11e8-8dc5-4bde87fbab11.png)

**Comment by TimotheeVille** [comment]
Awesome!
So we can close this issue?

**Comment by karthikprakash** [comment]
Yes, please. Thank you for your support and quick fix.
