### ISSUE TITLE
Error on the UI for an Unknow parameter _datatable in actionwords

### ISSUE THREAD

**Issue by karthikprakash** [hiptest/hiptest-issue-tracker#158]
### Steps to reproduce
1. Create a scenario using Hiptest APIs which contains a step table

### Expected behaviour
The Scenario should be successfully created with the step table configured

### Actual behaviour
Error is displayed "Unknown parameter(s) for actionword "<Step name>"" __datatable

When comparing the value of the step table along with the action word in the "Raw Version" in the Destination Project,  it appears to be exactly the same as the one in the Source project. 
Still, the error is displayed in the DEstination project and not in Source project. 

Refer the attached word document for the screenshots.
[Datatable Created for a Scenario in a Destination Project.docx](https://github.com/hiptest/hiptest-issue-tracker/files/2374901/Datatable.Created.for.a.Scenario.in.a.Destination.Project.docx)

**Comment by TimotheeVille** [comment]
It is expected. 
The scenario definition is only containing actionword calls. If you want to add a datatable to an actionword call, this specific actionword should have a datatable parameter.

What I suggest is to do an update of your actionword to add a datatable parameter to its definition.

PUT <actionword_url>
```
{
  "data": {
    "type": "actionwords",
    "id": <actionword_id>,
    "attributes": {
      "definition": "actionword 'actionword_name' (__datatable= \"||\") do\nend"
    }
  }
}
```

**Comment by HoudaDabou** [comment]
Hi @karthikprakash,

Did you have the opportunity to test the above proposal by @TimotheeVille?

Thanks in advance.

Regards,
Houda
