### ISSUE TITLE
400 error while opening hiptest from bookmark

### ISSUE THREAD

**Issue by sarikamhetre** [hiptest/hiptest-issue-tracker#161]
### Steps to reproduce
1. Hit https://app.hiptest.com/projects/47065/test-plan/folders/232921/scenarios/867766 url in chrome browser

### Expected behaviour
1. I should navigate to respective scenario

### Actual behaviour
1. I am gtting 400 error
### My configuration
**Browser:**
Crome browser Version 69.0.3497.100 
**Operating system:**
Mac os 10.12.6

**Comment by FatimaEzzahraIdrissi** [comment]
Hello @sarikamhetre,

I need more information about your project so i can investigate. Could you please contact us at support@hiptest.com?

Regards,
Fatima
