### ISSUE TITLE
Results pushed via hiptest-publisher using cucumber json --push-format updates the overall test status based on the last step status 

### ISSUE THREAD

**Issue by ramaniv** [hiptest/hiptest-issue-tracker#163]
### Steps to reproduce
1. Push results generated in cucumber json format via hiptest-publisher
2. refresh the test runs
3. if the status of the last step is **skipped**, and that of the previous step is **failed**, the overall test status is set to **skipped** instead of **failed**

### Expected behaviour
In the case described above, the last step is skipped because the previous step has failed. SO, the overall result should be failed instead of skipped.

### Actual behaviour
Tell us what happens instead

### My configuration
**Browser:**

**Operating system:**

**Comment by vincentcapicotto** [comment]
Hi ;)

we are working on it, we have found a solution and we will deploy in few hours.
We will ping you when is done, and if it's possible let us know if it's solved your issue

Regards

**Comment by ramaniv** [comment]
Hi Vincent, Thanks!! it worked. Closing this ticket
