### ISSUE TITLE
synchronization-information => synchronizing is always false

### ISSUE THREAD

**Issue by nchilders** [hiptest/hiptest-issue-tracker#165]
### Steps to reproduce
1. request test-run sync via API
2. check status of sync via API 

### Expected behaviour
syncing should report true when the synchronization is still in process. We have verified the invalid results by simultaneously checking the UI and the API.

### Actual behaviour
"synchronization-information"=> "synchronizing" is always false.

### My configuration
ruby CLI app

**Browser:**
chrome
safari
firefox

**Operating system:**
mac osx 10.13.6

**Comment by vincentcapicotto** [comment]
Hi,

I just deployed a fix for the issue, please could you test it and tell me if it's ok?

Thank you

**Comment by nchilders** [comment]
Seams to be working as expected! thanks for the quick turn around!
