### ISSUE TITLE
Strange parameters format in generated feature file

### ISSUE THREAD

**Issue by IvanK-01** [hiptest/hiptest-issue-tracker#167]
### Steps to reproduce
1. In BDD-style project create some folder.
2. Add scenario with datatable and some step that uses the table values.
3. Import feature file using https://hiptest.github.io/slate/#features API call.

### Expected behavior
Parameters escaped using triangular brackets in steps. As described in Gherkin reference:
https://docs.cucumber.io/gherkin/reference/
```
...
    Then I get <result> value from the test

    Examples:
      | result    |
      | "empty"   |
      | "results" |
```
### Actual behavior
```
...
    Then I get "<result>" value from the test

    Examples:
      | result  |
      | empty   |
      | results |
```

**Comment by HoudaDabou** [comment]
Hi,

Indeed this behaviour may seem abnormal, only we have consciously developed things this way for practical reasons.

Normally this is not a problem for the automate test execution in Gherkin, do you have any difficulties with this format generated during your execution?

Regards,
Houda

**Comment by IvanK-01** [comment]
This format is executed successfully. But it looked ugly and strange for me. I am creating tool for third-party users. I want to provide the best results to the users.

**Comment by IvanK-01** [comment]
You can add some parameter for
https://hiptest.github.io/slate/#features
if changing default behavior is not good thing by some reason.

**Comment by vincent-psarga** [comment]
We have just added in hiptest-publisher the possibility to select which character is used to delimit the parameters in Gherkin exports: https://github.com/hiptest/hiptest-publisher/commit/f08e8e22f3720019a53cce5a907190bb6a9fc089

Once this is released and deployed on the service version, we'll add the possibility to select in when downloading a feature (and so you will be able to remove the double-quotes around the parameters).
