### ISSUE TITLE
"Create" text boxes remains open 

### ISSUE THREAD

**Issue by erez-simplee** [hiptest/hiptest-issue-tracker#17]
When pressing the creating button (in sub folders and in scenarios) a text window pops to enter the name of the folder \ scenarios but when moving \ pressing to other parts in the page the text boxes remains open.

In the screen shot you can see that I am already writing description to test and the boxes are still there 

![screen shot 2016-08-10 at 3 07 24 pm](https://cloud.githubusercontent.com/assets/20947192/17553095/8494eff8-5f0c-11e6-9d5b-25e7aa19bc1e.png)

**Comment by severinedarlot** [comment]
Hello @erez-simplee,

thanks for this return. The issue has been fixed on Hiptest cloud. It will be fixed in Hiptest on-premises version 0.9.62.

Enjoy!

Séverine
