### ISSUE TITLE
Get .feature files for specific test run

### ISSUE THREAD

**Issue by IvanK-01** [hiptest/hiptest-issue-tracker#171]
https://hiptest.github.io/slate/?http#get-feature-from-a-given-folder
request returns current version of scenarios. But test run contains some old version of scenarios. We need the same functionality for test folders.

Something like:
https://app.hiptest.com/api/projects/<project_id>/test_runs/<test_run_id>/folder_snapshots/<folder_snapshot_id>/feature

**Comment by aurelien-reeves** [comment]
That looks a lot like what [hiptest-publisher](https://github.com/hiptest/hiptest-publisher) actually does.
Would you have the ability to use [hiptest-publisher](https://github.com/hiptest/hiptest-publisher) for that kind of use instead of the API?
