### ISSUE TITLE
Post results to test run that is created using "Tests that have not been written within Hiptest" option

### ISSUE THREAD

**Issue by IvanK-01** [hiptest/hiptest-issue-tracker#173]
User can select "Tests that have not been written within Hiptest" during creation test run. But my tool is failed to post to this test run using any APIs from
https://app.hiptest.com/api/

I know about
https://hiptest.net/import_test_reports/$SECRET_TOKEN/105/junit
but this way is not looked good because my tool is need to create some XML and emulate some external tool format (for example JUnit).

**Comment by HoudaDabou** [comment]
Hello Ivan,

You have the possibility to use our open-source tool named [Hiptest-publisher](https://github.com/hiptest/hiptest-publisher) for automation.

This one allows you, among other things, to push your tests results _(your Junit file)_ as shows you [this short video](https://downloads.intercomcdn.com/i/o/85855878/81df50285eef7d7085e21e47/push_result.mp4).

Hope this helps you :)

Feel free to contact us if you need any assistance to install Hiptest-publisher.

Regards,
Houda

**Comment by HoudaDabou** [comment]
I understand your concerns. For now we do not provide a way to push tests to an external test run through the API. I'll propose this functionality to our product owner for consideration.

For now you can only push test with the URL you forementioned. Indeed pushing results in JUnit format can be tedious. Maybe you should consider pushing them in [TAP format](https://testanything.org/).

A typical TAP file looks like this:
```
1..5
ok 1 - This test passes
not ok 2 - This one fails
ok 3 - This one passes too
    This is a comment
    for test 3
ok 4 - This one is skipped  # SKIP
ok 5 - This one passes # This is a comment an won't be part of the test name.
```

The downside is that it lacks hierarchy.

Would that fit your needs until we develop something more specific in the API?

**Comment by IvanK-01** [comment]
We investigate TAP and JUnit formats and try posting test results via CURL.
Unfortunately we are not found some documentation about the formats fields mapping.
Such as binding names in tests result file with scenarios in Hiptest.

The most hard case is scenario outline. Could you provide some example for this case?

**Comment by HoudaDabou** [comment]
Sure, I'm going to consult our dev team and will get back to you quickly with their recommendations.

Thanks Ivan for your understanding.
