### ISSUE TITLE
Autoload of scenarios prevent viewing revision history

### ISSUE THREAD

**Issue by nchilders** [hiptest/hiptest-issue-tracker#174]
When I create a test run to use for regression testing I am unable to access the revision history of the test run due to infinite autoloading of scenarios
### Steps to reproduce
1. create a test run with > 2000 scenarios
2. make some changes
3. try to access revision history

### Expected behaviour
I should be able to access revision history, ideally without needing to scroll through every scenario listed on the test run.

### Actual behaviour
I scroll through ~1/2 of the scenarios and it appears to hit some sort of limit. It acts like its loading more scenarios but no additional scenarios appear as a result I am unable to access any revision history for the test run.

### My configuration
**Browser:**
Chrome 70.0.3538.102
**Operating system:**
Mac OSX 10.14.1

**Comment by HoudaDabou** [comment]
Hi,

We'll reproduce you use case and get back to you ASAP.

Thanks for your understanding.

Regards,
Houda

**Comment by HoudaDabou** [comment]
Hello,

Our team has fixed this bug, please refresh your browser and try again this handling.

Then could you confirm if this fix has resolved your issue?

Thanks in advance.

Regards,
Houda
