### ISSUE TITLE
An error occured while generating the code, please contact support@hiptest.net for analysis

### ISSUE THREAD

**Issue by IvanK-01** [hiptest/hiptest-issue-tracker#175]
Sometimes *.feature file returned by /api/projects/<project_id>/folders/<folder_id>/feature contains text like:

> Feature: Test feature
> Errors were found when generating the feature file:
> - An error occured while generating the code, please contact support@hiptest.net for analysis.

Before this message API response continues for about 5 seconds.
This issue hasn't stable reproducible way.

**Comment by HoudaDabou** [comment]
Hi Ivan, 

Could you contact HipTest support via this email: support@hiptest.com 

It will be more convenient channel to discuss about this issue.

Thanks in advance.

**Comment by IvanK-01** [comment]
Done, please see email "An error occured while generating the code".
