### ISSUE TITLE
Generating back up

### ISSUE THREAD

**Issue by vicky18782** [hiptest/hiptest-issue-tracker#177]
### Steps to reproduce
1. Open hiptest and login
2. Click on the project
3. On the right Click on back up
4.  From the pop up menu click on Generate Back up
5. It will say back up in progress

### Expected behaviour
Back up should be generated (download last back (back up generated date)

### Actual behaviour
It initiates the back however if we visit the next day the current back up is not displayed, instead the old back is always displayed

### My configuration
Chrome: Version 72.0.3626.109

**Operating system:**
Windows 10

**Comment by cbliard** [comment]
Hello Vicky,

Can you tell us your project id? (It's in the address bar of your browser)

Regards

**Comment by vicky18782** [comment]
37282

**Comment by vicky18782** [comment]
> Hello Vicky,
> 
> Can you tell us your project id? (It's in the address bar of your browser)
> 
> Regards

**Comment by vicky18782** [comment]
37282

**Comment by HoudaDabou** [comment]
Thanks Vicky!

Our team'll investigate about your issue and we'll get back to you ASAP.

Regards,
Housa

**Comment by HoudaDabou** [comment]
Hello @vicky18782,

Good news, our team has taken the necessary action to fix this issue.

May you try out to generate a backup and let us know about the result please?
