### ISSUE TITLE
Feature Request: Have capability to send description through the create a test run API call

### ISSUE THREAD

**Issue by raseel-mohamed** [hiptest/hiptest-issue-tracker#178]
We have an automated workflow. Once the application under test (AUT) is deployed travis kicks of the hiptest test suite and the results are uploaded back to hiptest. 

Once we have a bunch of test runs it becomes difficult to pinpoint which execution result maps to the version of AUT. If there is another value that we can send along with the command

```
hiptest-publisher -t <HIPTEST_TOKEN> -c hiptest-publisher.conf --test-run-id=<TEST_RUN_ID> --push="result.json" --push-format=cucumber-json
```
Something like `--build` flag that can be viewed from the execution history for each run. 

 ### Steps to reproduce
1. Run automated tests from travis. 
2. Upload json result to the test suite with test id

**Comment by HoudaDabou** [comment]
Hi @raseel-mohamed,

So you can add comment with a specific indication as "build # 123", for each test case in your tests results file (report.json) to get the relative indication in each comment of test case from HipTest.

Does this meet your need?

Regards,
Houda

**Comment by raseel-mohamed** [comment]
@HoudaDabou, thank you for the prompt response. Unfortunately that is not a solution we want to implement.

Having said that, I found a better solution in your API documentation. We can [Create a test run](https://api-doc.hiptest.com/#create-a-test-run) through api with the build name and add our scenarios to it before execution. However, is it possible to add a description for the test run in the api request. The documentation does not suggest any value that can be used to populate the *Description* field of the test run.

If you want I can close this ticket as resolved and open another enhancement request to add description when creating a test run.

Thanks and regards,
Raseel Mohamed

**Comment by HoudaDabou** [comment]
Hello @raseel-mohamed,

Thank you for this explanation!

So, at this time you can't add description when you create a test run via the API, but maybe soon this will can possible :)

We'll let you know about its progress!

Regards,
Houda

**Comment by raseel-mohamed** [comment]
May be I should change the title and the actual issue to make it more readable for you guys and anyone who has a similar issue.

Thanks a lot, @HoudaDabou

**Comment by HoudaDabou** [comment]
Hi again @raseel-mohamed!

Our team has added the possibility to include description when creation a test run, here is the related [endpoint](https://api-doc.hiptest.com/#create-a-test-run).

So, I close this issue and if you notice any inconsistency -> feel free to reopen it.

Hope this meets your expectations.

Kind regards,
Houda

**Comment by raseel-mohamed** [comment]
@HoudaDabou, thank you very much for this
