### ISSUE TITLE
Synchronise Test Runs Occasionally Taking Ages

### ISSUE THREAD

**Issue by GraemeBrooke** [hiptest/hiptest-issue-tracker#179]
### Steps to reproduce
1. Make a change in Test Scenarios
2. Go to Associated Test Run
3. Click on horizontal 3 dots button & Synchronise & resultant Confirmation boxes
4. Normally, it synchronises quickly in a minute or so BUT occasionally it has rotating whirlygig and remains in this status without updating test for ages

### Expected behaviour
Should synchronise within a short space of time

### Actual behaviour
 occasionally it has rotating whirlygig and remains in this status without updating test for ages

### My configuration
**Chrome:**

**Operating system:**

**Comment by HoudaDabou** [comment]
Hi @GraemeBrooke,

May you grant access to HipTest support to your project to allow us better investigate this issue please?

This option is available from the help menu at the bottom left of the screen:
​
![grant_access_support](https://user-images.githubusercontent.com/43133237/53994740-5ebb9500-4133-11e9-8c3c-1a32555f73d1.png)

Thanks in advance.

Regards,
Houda

**Comment by HoudaDabou** [comment]
Hi again @GraemeBrooke,

Any update on this issue?

**Comment by GraemeBrooke** [comment]
Hi Houda
Sorry I have only just replied – I was out of office since Thursday lunchtime & this is my first time back
It had rectified over the last few days and I have just ran another Synchronise against same Test Run just now and it synchronised successfully in around 2 minutes
As I said previously this only occurs occasionally but is a real pain when it does
What is the fastest way to flag this when it occurs again please?
Have you not had this reported by anyone else before?

Thanks

Graeme

Graeme Brooke
Test Analyst

[cid:image001.png@01D4D7D8.10F70940]

[cid:image002.png@01D48D45.91AB00B0]
Access UK Ltd l Weavers Mill l Haverhill l CB9 8DD
T: +44 (0)1440 766400 l www.theaccessgroup.com<http://www.theaccessgroup.com/> l www.icarehealth.co.uk

[Assets/DontPrintTree_icon.png]Please consider the environment and don't print this e-mail unless you really need to.

The information in this internet email is confidential and is intended solely for the addressee. If you have received it by mistake please let us know by e-mail reply and delete it from your system

**Comment by HoudaDabou** [comment]
Hi @GraemeBrooke,

No problem :) 

Yes, this problem has occurred before and normally our team has fixed it.

To allow us to better investigate this issue: as soon as the problem occurs again, please send us an email to support@hiptest.com

In any case, thank you for your feedback :+1: 

I'll close this issue but as said before, feel free to contact us by email.

Regards,
Houda
