### ISSUE TITLE
Hiptest wont update on JIRA cloud

### ISSUE THREAD

**Issue by angell-ec** [hiptest/hiptest-issue-tracker#18]
> The add-on host returned HTTP response code 403 when we tried to contact it during installation. Please try again later or contact the add-on vendor.

![manage_add-ons_-_jira](https://cloud.githubusercontent.com/assets/10407905/17703738/6ab0ecc8-6398-11e6-85c7-ee7943cb44a5.jpg)

**Comment by cbliard** [comment]
We have just released a fix for this issue. Can you try again please?

**Comment by angell-ec** [comment]
Great, it updated!
