### ISSUE TITLE
Enhancement request: SAML support 

### ISSUE THREAD

**Issue by ramaniv** [hiptest/hiptest-issue-tracker#180]
### Steps to reproduce
It will be great if we hiptest has SAML support. We can then integrate hiptest to any SSO application.

**Comment by HoudaDabou** [comment]
Hi @ramaniv,

Our team has added this feature request in our backlog, you can find the related Trello card [here](https://trello.com/c/Haz54W2Y).

Please upvote for it to increase its priority in our production.

Thanks in advance for your vote!

Regards,
Houda

**Comment by HoudaDabou** [comment]
Hi again @ramaniv,

Feel free to follow the progress of its development from our [backlog](https://trello.com/b/sSdBSlL0/hiptest-what-we-are-cooking-up).

So, I close this issue.

Regards,
Houad
