### ISSUE TITLE
How can i identify if and where this is being used in any project?

### ISSUE THREAD

**Issue by jward53** [hiptest/hiptest-issue-tracker#181]
### Steps to reproduce
HipTest has been installed and need to identify where/if it is being used by any projects.

### Expected behaviour
Need to know where it is being used and how to identify that throughout the system

### Actual behaviour
Just need to know since this has been installed how to identify where it is being used..

### My configuration
**Browser:** Jira CLOUD

**Operating system:**

**Comment by HoudaDabou** [comment]
Hi,

Can you give me more details about the context please?

So, I understand that you had installed the HipTest add-on from your instance Jira Cloud, right? 

Can you make this following sentence better clear please: "Need to know where it is being used and how to identify that throughout the system"  -> From which system do you want to detect these information, from your HipTest account or from your Jira instance?

Thanks in advance.

Regards,
Houda

**Comment by HoudaDabou** [comment]
Hi @jward53,

So I close this issue, please reopen it if you want to give it more details.

Regards,
