### ISSUE TITLE
When pushing to hiptest 0 test are imported

### ISSUE THREAD

**Issue by srotak5** [hiptest/hiptest-issue-tracker#182]
### Steps to reproduce
When i followed this tutorial 

https://hiptest.com/blog/hiptest/test-automation-with-hiptest-from-test-design-to-ci/ 

Everything worked test passes, but when i wanted to post results to hiptest i got 0 test imported. 

### Expected behaviour
Post results to hiptest

### Actual behaviour
![error](https://user-images.githubusercontent.com/11695596/56192362-73425580-602e-11e9-93a5-3fc8a8a6e72d.jpg)
 
Cmd...

[v] Posting target/surefire-reports/TEST-com.coffeemachine.CoffeeMachineTest.xml to https://app.hiptest.com
[v] 0 tests imported
Possible causes for the lack of imported tests:

  * Did you run the following command before executing your tests?
    hiptest-publisher --config=hiptest-publisher.conf --without=actionwords --test-run-id=<the ID of the test run you want to push the results to>

  * Did you specify the correct push format?
    Use push_format=<format> in your config file or option --push-format=<format> in the command line
    Available formats are: cucumber-json, junit, nunit, robot, tap

Suggested actions didnt help.

### My configuration
**Browser:** 
Chrome mostly 

**Operating system:**
Win 10

**Comment by HoudaDabou** [comment]
Hi @srotak5,

So, you need to specify a test run ID.

We'll summarize together:

1. From your test run overview, you find the commands lines for automation: after clicking on the 3 dots options and selecting "Automate":

![automate_option](https://user-images.githubusercontent.com/43133237/56235140-1aeb7200-6087-11e9-940e-12d9fe633cf6.png)

2. From the open modal, you find the two needed commands lines to update your features files and push your tests results files:

![tr_automate](https://user-images.githubusercontent.com/43133237/56235194-3bb3c780-6087-11e9-9f9a-77ab25d9f66e.png)


3. Add your project token and site parameters to your hiptest-publisher config file as this:

```
token=  <my_project_token>
site = 'https://app.hiptest.com'
```
![secret_token](https://user-images.githubusercontent.com/43133237/56235926-b6311700-6088-11e9-9661-4e086cc72bec.png)

4. Run this below command line to update your tests and fetch UIDs for each one of your scenarios:

`hiptest-publisher -c hiptest-publisher.config --without=actionwords --test-run-id=<you_test_run_ID>`

5. Build your tests to generate your report file(s) with UIDs and run this below command:

`hiptest-publisher -c hiptest-publisher.config --test-run-id=<you_test_run_ID> -p target/surefire-reports/TEST-com.coffeemachine.ProjectTest.xml --push-format junit`

Here is a recent tutorial regarding automation: https://hiptest.com/start/tutorials/ci-in-5-minutes-flat/

And here is a webinar's recording made by one of our experts about "[Automate your Tests at the Speed of Agile](https://smartbear.zoom.us/recording/play/AtE2f2yx3eCwPwL34bp0bso_4GueGJN9bSwqiQuttZ7MYG74HpX6VqBVlGqccCHn?continueMode=true)".

Also, we regularly schedule webinars on automation or BDD, feel free to register to ask your questions directly to our experts, at the bottom of [this page](https://hiptest.com/start/).


Feel free to ask us more details if you need :) 

Regards,

**Comment by srotak5** [comment]
Hi @HoudaDabou 

Thank you for your reply.

I did all the steps you suggested even before. I created scenario, testrun etc.. i ran mvn package and tried to post the test to hiptest via publisher command you suggested, it worked once and just once.
Then i tried to add new action to my scenario on hiptest and did the whole process again and now i cant post it i still get that 0 tests are imported even when i get notification on hiptest that test is running. 

![ButWhyyyy](https://user-images.githubusercontent.com/11695596/56264865-1d31e880-60e8-11e9-95c0-aec09062bd16.png)

Please help meee :D

**Comment by HoudaDabou** [comment]
Hello,

Okay, can you send me your hiptest-publisher config file and your tests results file (.XML) to support@hiptest.com please?

**Comment by srotak5** [comment]
Done :)

**Comment by HoudaDabou** [comment]
Hi again,

Did you receive my last answer by email? If so, did you succeed in achieving the expected result?

**Comment by srotak5** [comment]
Hi

In sorry i had to leave work early and we have easter holidays till tuesday
so i cant really tell u when ill be able to try it.

Can i contact you then ?

Thank youbvery much for your help so far

**Comment by HoudaDabou** [comment]
Yes sure :)

So let me know and happy holidays!

**Comment by srotak5** [comment]
Everything works <3

**Comment by HoudaDabou** [comment]
Great :)
