### ISSUE TITLE
Arrow keys switch test when in comment field 

### ISSUE THREAD

**Issue by andreasholl** [hiptest/hiptest-issue-tracker#184]
### Steps to reproduce
1.go to any test
2.click resume test
3.go to the comment field, click it, write some comment text, preferably with a typo :), 
then try to use left/right arrow to navigate back and fix it

### Expected behaviour
I should be able to scroll through my text in the comment field

### Actual behaviour
The overall "arrow key means jump to previous/next testcase"-mechanic kicks in and im in the
previous testcase instead of 2-3 characters before to fix my spelling mistake

### My configuration
Chrome
Win10

**Comment by HoudaDabou** [comment]
Hi,

Can you confirm me that you did this [handling](https://smartbear.box.com/s/il2qqqt5owg78u66lh2pf4nun5lvaxqt) please?

Thanks in advance.

**Comment by andreasholl** [comment]
Hi Houda,

or Dabou?,

I can confirm, I just did that and it works.
But that’s not the point.
To stay with your video example, click on your lorem Ipsum text in the comment, and while there, press the left arrow key.
This will trigger a jump to the previous testcase, which it shouldn’t.
While in the comment field, I would like to be able to use the arrow keys to navigate the text I have written.
(example – go back a few characters and delete a typo).
The changing testcases with arrow keys while outside the comment field works fine.
But within the comment field the cursor should be captured and arrow key commands not given to the testcase-jumping routine.

Hope that helps/clarifies 😊
If not, feel free to ask again

And thanks for looking into it so fast,
Best regards,
Andy

**Comment by HoudaDabou** [comment]
Hi Andy,

Yes I see what you mean now, thanks for this explanation.

And you're correct: this is a bug!

So, we created a private ticket to solve this one ASAP.

Thanks for the bug report Andy :) we'll keep you informed about the deployment of its fix.

Kind regards,
Houda

**Comment by andreasholl** [comment]
Happy to help 😊

**Comment by HoudaDabou** [comment]
Hello Andy,

Our team has fixed this bug, may you check if all is right after refreshing your browser please?

Thanks in advance!

**Comment by andreasholl** [comment]
Hi Houda,

I just checked and its fixed.
Thank you very much and have a nice day 😊

Andy

**Comment by dimitriSaplatkin** [comment]
Thanks for fixing the bug. But now switching test cases with arrow keys is not working anymore.

**Comment by HoudaDabou** [comment]
Hi Dimitri,

Yes you're correct, we have chosen to deactivate this option.

Thanks for your understanding :)

Regards,
Houda
