### ISSUE TITLE
What version (cloud or server) do we use with Jira server? Is the cloud version an option?

### ISSUE THREAD

**Issue by GusPoblete** [hiptest/hiptest-issue-tracker#185]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### My configuration
**Browser:**

**Operating system:**

**Comment by HoudaDabou** [comment]
Hi @GusPoblete,

You can use the both versions: Cloud or Server. 

Here is the section dedicated to Jira integration in our documentation: https://hiptest.com/docs/integrate-with-jira/

Feel free to ask us more details :)
 
Regards,
