### ISSUE TITLE
Can't Determine Test Assignee

### ISSUE THREAD

**Issue by Phwop** [hiptest/hiptest-issue-tracker#186]
### Steps to reproduce
1. Create a test run
2. Assign a user a subset of tests
3. Enter user email in search

### Expected behaviour
All tests assigned to user w/ entered email should display as search results.

### Actual behaviour
Not all tests assigned to user w/ entered email display as search results.

### My configuration
**Browser:**
Chrome 74

**Operating system:**
macOS Sierra 10.12

**Comment by HoudaDabou** [comment]
Hi!

May you send us an email at support@hiptest.com to investigate your issue please?

Thanks in advance.

**Comment by HoudaDabou** [comment]
Hi @Phwop,

Any update on this issue?

I'll close it and feel free to reopen it :)
