### ISSUE TITLE
[API] create_from_feature size limit?

### ISSUE THREAD

**Issue by timdouglas** [hiptest/hiptest-issue-tracker#187]
I'm seeing 500 responses from API calls to create_from_feature where the feature file is >50 lines long.

### Steps to reproduce
1. POST a feature > 50 lines
2. 500 response (in HTML)

### Expected behaviour
create_from_feature to allow a full feature file to be sent and scenarios etc to be created as normal on hiptest.

### Actual behaviour
if feature file is >50 lines, a 500 response in HTML is returned:

```html
<div class="o-maintenance__wrap">
  <div class="o-maintenance-error">
    500
  </div>

  <div class="dialog">
    <h1 class="f-title-l">We're sorry, but something went wrong.</h1>
      <p>
        An error has occured and our team is working to fix the problem.
      </p>
      <p>
        If you need immediate help, please contact <a href="mailto:support@hiptest.com">support@hiptest.com</a>
        </p>
      </div>
  </div>
```

### My configuration
**Browser:** REST API

**Operating system:** macOS Mojave

**Comment by blethier** [comment]
Hi,

We will investigate on this issue, could you contact us directly at support@hiptest.com please ?

Regards.

**Comment by timdouglas** [comment]
Will do, ta
