### ISSUE TITLE
Test Run Refresh

### ISSUE THREAD

**Issue by GraemeBrooke** [hiptest/hiptest-issue-tracker#188]
### Steps to reproduce
1. Update Test Status in Test Run 
2. Test Run Totals taking a while to update & Total Disk blank & Grey until updates
3. Also when exit Test Runs & Return, takes quite a while for all Test Runs to appear
4. Only started occurring this week

### Expected behaviour
Almost instant response when arrive on page

### Actual behaviour
Very slow response

### My configuration
**Chrome IE11 & Edge

**Operating system:**
Windows 10

**Comment by HoudaDabou** [comment]
Hi @GraemeBrooke!

We need to have access to your project to better investigate, can you contact the support (support@hiptest.com) please?

Thanks in advance :)

**Comment by vincentcapicotto** [comment]
Hi, 

we have corrected a bug which can be related to this issue.
Please, could you try again and tell me if it's better now?

**Comment by GraemeBrooke** [comment]
Hi Vincent
It hadn’t cured at time of your email and was still bad intermittently yesterday, however today touch wood seems to be behaving itself so far
Thanks
Graeme

Graeme Brooke
Test Analyst

[cid:image001.png@01D53C9F.A2734E70]

[cid:image002.png@01D48D45.91AB00B0]
Access UK Ltd l Weavers Mill l Haverhill l CB9 8DD
T: +44 (0)1440 766400 l www.theaccessgroup.com<http://www.theaccessgroup.com/> l www.icarehealth.co.uk

[Assets/DontPrintTree_icon.png]Please consider the environment and don't print this e-mail unless you really need to.

The information in this internet email is confidential and is intended solely for the addressee. If you have received it by mistake please let us know by e-mail reply and delete it from your system

**Comment by HoudaDabou** [comment]
Great! Thanks @GraemeBrooke for the feedback =)
