### ISSUE TITLE
Tags on folders don't seem to cascade

### ISSUE THREAD

**Issue by adamlacoste** [hiptest/hiptest-issue-tracker#19]
When I add a tag to a scenario in HipTest (e.g. "adblock") and download the Gherkin feature spec, I can see that tag appear above the scenario heading as `@adblock`.

However, when I add a tag to a folder (whether it's functioning as a feature or a directory of features), that tag doesn't appear anywhere in the resulting Gherkin spec.  It's not present at the feature heading level nor at the scenario heading.  It seems to just get lost.

If it's relevant, I'm using BDD mode and the SAAS web interface for HipTest Publisher.

**Comment by severinedarlot** [comment]
Hello Adam, the issue should be fixed with the version 0.18 of the hiptest-publisher.
Cheers
