### ISSUE TITLE
Jira issue creation: user picker field issue

### ISSUE THREAD

**Issue by aurelien-reeves** [hiptest/hiptest-issue-tracker#191]
When creating a jira issue from HipTest, if a user picker field is mandatory, it is required in the form.

The auto-completion seems to be broken:
- one specific authorization is required on Jira for the auto-completion to work: the add-on requires the ability to browse users
- the display of users in the list is glitched as shown on the following pictures
- when selecting a user in the list, nothing happened, the field is not completed

![image](https://user-images.githubusercontent.com/24386780/62298409-4302b380-b473-11e9-836b-295c5dcf3d44.png)

**Comment by HoudaDabou** [comment]
This issue has been solved!
