### ISSUE TITLE
Hiptest publisher as cucumber json output doesnt work

### ISSUE THREAD

**Issue by guillaumeray** [hiptest/hiptest-issue-tracker#192]
### Steps to reproduce
1. Create a test run in hiptest  
2. go to project and write 
`hiptest-publisher --config-file myconf.conf --test-run-id 290387 --without=actionwords`
3. I run my test with a cucumber json output
4. I want to publish my test result on hiptest 
`hiptest-publisher --config-file myconf.conf --push test-report/json/login.json --test-run-id 290387 --push-format cucumber-json`

### Expected behaviour
Test result are pushed in test run 

### Actual behaviour
No tests imported

Error message : 
````
[v] Posting test-report/json/login.json to https://app.hiptest.com
[v] No tests imported
Possible causes for the lack of imported tests:

  * Did you run the following command before executing your tests?
    hiptest-publisher --config=hiptest-export/hiptest-publisher.conf --test-run-id=290387 --without=actionwords


  * Did you specify the correct push format?
    Use push_format=<format> in your config file or option --push-format=<format> in the command line
    Available formats are: cucumber-json, junit, nunit, robot, tap
````

### My configuration
**Browser:** Chrome 76

**Operating system:** Mac OS X

**cucumber json report**
```
[{"keyword":"Feature","description":"","line":1,"name":"login","uri":"Can not be determined","tags":[],"elements":[{"keyword":"Scenario","description":"","name":"Login as admin (uid:017e8a4e-44d0-48b4-ad54-91fa767435d2)","tags":[],"id":"login;login-as-admin-(uid:017e8a4e-44d0-48b4-ad54-91fa767435d2)","steps":[{"arguments":[],"keyword":"Given","name":"I login meero with mail \"admin@meero.com\" password \"123456\"","result":{"status":"passed","duration":3000000},"line":8,"match":{"location":"can not be determined with webdriver.io"}},{"arguments":[],"keyword":"Then","name":"I should be on admin page","result":{"status":"passed","duration":1000000},"line":9,"match":{"location":"can not be determined with webdriver.io"}}]}],"id":"login","metadata":{"browser":{"name":"chrome","version":"76.0.3809.87"},"device":"Device name not known","platform":{"name":"Platform name not known","version":"Version not known"}}}]
```

**Comment by HoudaDabou** [comment]
Hi @guillaumeray,

Can you send us your hiptest-publisher config file by email to: support@hiptest.com please?

**Comment by HoudaDabou** [comment]
Hi again Guillaume!

Thanks for the config file!

So after checking your JSON report file, I noticed that this one doesn't have the right format of cucumber-json.

You find [here](https://smartbear.box.com/s/8to209e783wg2wtwhcvr6b1t4z7rkvsy) an example of a JSON report file that has the right format/the supported format by HipTest. This file has been generated from [this example project based on cucumber-java](https://github.com/hiptest/hps-cucumber-java) and the "Coffee machine" sample project.

Please let me know if this helps you :)

**Comment by guillaumeray** [comment]
Thank you very much, i was expecting this kind of issue as json report can have several format. I will find a way to generate a report with the good format.
