### ISSUE TITLE
ActionWord unmatched when starting with "given", "when" or "then"

### ISSUE THREAD

**Issue by ylacaute** [hiptest/hiptest-issue-tracker#196]
### Steps to reproduce
1. Create an actionWord "whenMyAction"
2. Create a new step, type "whe" (=> the previous actionWord is matched, that is ok)
3. Continue by typing "n"

### Expected behaviour
The "whenMyAction" should still be matched

### Actual behaviour
There is no more match

### My configuration
**Browser:** -- 

**Operating system:**
Debian

**Comment by HoudaDabou** [comment]
Hi @ylacaute,

Can you contact the support by email at: support@hiptest.com please? We need to access to your project to better investigate your issue =)

**Comment by ylacaute** [comment]
I discovered something else : when editing a new step, if you first write the "action type" then the actionWord the completion works correctly.

Let's say you already have a registered actionWord "givenSomething", and you creating a new step :
 - you write "give" => completion on the "givenSomething" appears
 - you write "given" => no completion at all (because given is an exact match)
 - you write "given g" => completion on the "givenSomething" appears and stay as long character match, as exepected.

So, I think you should not waste time with that and you should close this issue, that is an acceptable bahaviour !

**Comment by HoudaDabou** [comment]
Okay for letting us know =)
