### ISSUE TITLE
Missing documentation on data-table (404)

### ISSUE THREAD

**Issue by ylacaute** [hiptest/hiptest-issue-tracker#197]
### Steps to reproduce
1. Go on page https://hiptest.com/docs/create-scenarios/
2. Click on the link : See Datatable section.

### Expected behaviour
The datatable doc section

### Actual behaviour
404

### My configuration
**Browser:** --

**Operating system:**
Debian

**Comment by HoudaDabou** [comment]
Hi again Yannick! 

Thank you so much for the feedback =) we changed it!

You find [here](https://hiptest.com/docs/use-datatable/) the dedicated part of documentation to how use the datatable.

Also, from the app, you find this link here:

![datatable_link](https://user-images.githubusercontent.com/43133237/66325131-047fee00-e927-11e9-8413-2aee9bd50825.gif)
