### ISSUE TITLE
Error in ifthen.hbs (java)

### ISSUE THREAD

**Issue by ylacaute** [hiptest/hiptest-issue-tracker#198]
In the current java template "ifthen.hbs" :
```handlebars
if ({{{ rendered_children.condition }}}) {{#curly}}
{{#indent}}{{#each rendered_children.then}}{{{this}}}
{{/each}}{{/indent}}
{{#if has_else?}}} else {
{{#indent}}{{#each rendered_children.else}}{{{this}}}
{{/each}}{{/indent}}
{{/if}}{{/curly}}
```
If think this line is incorrect : 
```handlebars
{{#if has_else?}}} else {
```

**Comment by vincent-psarga** [comment]
Hi,

What would be incorrect exactly ?
If it is the extra closing curly bracket, it's now possible to use them in templates (under certain conditions).

**Comment by ylacaute** [comment]
Ok I thought you had to use
```handlebars
{{/curly}} else {{#curly}}
```
Indeed, this file is detected in error in Idea Intellij with the handlebars plugin.
I let you close this issue if you think it is not necessary to change it.

**Comment by vincent-psarga** [comment]
The support of curly braces in handlebar template is pretty recent (and there's still some cases when it is still necessary to use the `curly` helpers).

That said, in that particular case, I'm not sure I should have used the bracket. I though it would make the template more readable, but if IDEs mark them as errors it may be better to revert to `curly` helpers.
