### ISSUE TITLE
Enhancement : Allow Call to Jenkins Jobs to take parameters

### ISSUE THREAD

**Issue by ntynen** [hiptest/hiptest-issue-tracker#20]
I would like to be able to pass in parameters to a Jenkins job from a Test Run in Hiptest. 

My Jenkins job has to take parameters for the following reasons:
- I have many QA environments (currently 14)
- I have approximately 150 test suites, covering 3 products
- I allow the users to set a repo and branch for circumstances including bug fixes and so the automation engineers can test new code prior to it being merged with the master branch

<img width="1037" alt="screen shot 2016-10-25 at 4 40 46 pm" src="https://cloud.githubusercontent.com/assets/4174747/19708244/f64acb62-9ad1-11e6-8775-f024b246ddf2.png">

**Comment by ntynen** [comment]
@severinedarlot @aurelien-reeves Is there any update on this. It would be very helpful to my team if we could run our Jenkins automation test suites straight from Hiptest.

**Comment by jracenet** [comment]
The support for Jenkins parameters has been released this month :)
Enjoy testing!
