### ISSUE TITLE
Attachment file are not exported

### ISSUE THREAD

**Issue by ylacaute** [hiptest/hiptest-issue-tracker#201]
### Steps to reproduce
1. Create a scenario with an attachment
2. Export the projet (or just update with the publisher)

### Expected behaviour
To have the attachment file (in the exported zip or downloaded with publisher)

### Actual behaviour
No attachement at all

### My configuration
**Browser:** - 

**Operating system:**
Debian

**Comment by HoudaDabou** [comment]
Hi Yannick! 

Yes sadly we're aware about this :( 

Our team has already added this feature request to our backlog, you find [here](https://trello.com/c/YIw6fZ69) the corresponding Trello card.

Please upvote for it to increase its priority in our production.

Thanks in advance for your vote and your understanding.
