### ISSUE TITLE
String concatenation generate a wrong warning in GUI

### ISSUE THREAD

**Issue by ylacaute** [hiptest/hiptest-issue-tracker#205]
### Steps to reproduce
1. Create an actionword "MyActionWord" with a parameter "test"
2. As parameter value, put this value: =('AAA' + 'BBB')

### Expected behaviour
No warning should appear since this concatenation is correct. We can even add variables in this concatenation and the generate code is still valid (in Java Junit, maybe not for other langage IDK).
For example =('AAA' +  aGivenParamFromParentActionWord + 'BBB') will generate a valid Java code.

### Actual behaviour
We got a WARNING in the GUI 
_In Scenario "MyActionWord": expected Integer or Float, got String_
Moreover, we are not able to view test anymore (only edit view is working).

**Comment by HoudaDabou** [comment]
Hi @ylacaute,

Do you mind to grant access to HipTest support to your project to allow us to investigate please? 
_(This option is only available for project admin)_

![grant_access_support](https://user-images.githubusercontent.com/43133237/69347942-a4929c00-0c75-11ea-8775-dcd989a175f2.png)

**Comment by ylacaute** [comment]
Hi again, did you have time to investigate ?

This feature is important as soon as we are playing with composed ActionWord, which is a important strength of HipTest. We are convinced that this feature allow us (+ custom handlebars templates) to generate directly executable code with a minimum effort.
I hope it is not a big deal to adapt the Hipest UI, as a lot of langage accept string concatenation with char '+'.

Thanks

**Comment by HoudaDabou** [comment]
Hi Yannick,

As mentioned in my previous email, a temporarily solution to solve this issue is to remove the equal character to get that value: ('AAA' + 'BBB') instead of that one: =('AAA' + 'BBB')

![aw_parameter_value](https://user-images.githubusercontent.com/43133237/69762767-87753600-116b-11ea-87b7-b8ef5e4a8e0c.png)


As you notice on the following screenshot, after removing the equal character = of the actionword parameter value, the error message disappears:

![yannick_param_value](https://user-images.githubusercontent.com/43133237/69762944-01a5ba80-116c-11ea-8e2c-0bd3b968b984.png)

Does that workaround suit you? 

However, we opened a private issue to fix that issue ASAP.
Kind regards,
Houda

**Comment by ylacaute** [comment]
Awesome ! 
Without this '=', no warning anymore, the "view tests" is working again and the generated code is still valid. The parameter inside the concatenation is not resolved in the "view tests" but it is not critical at all !
I let you close this issue if you think it is ok.
Thanks you

**Comment by HoudaDabou** [comment]
Thanks for the feedback Yannick!

I checked your scenario a few minutes ago and the "view tests" works well, if you still encounter the issue => may you try out to refresh your browser? 

Anyway, I close the issue :slightly_smiling_face:

**Comment by ylacaute** [comment]
Hi again,
I am very sorry to come back here again, but this issue should be re-opened: I forgot to "re-synchronize" in the test-run view before testing, that's why it was working as expected.

When we suppress the '=' character, the generated code is not good (it generate a single string as argument).

**Sample code generated:** "('aaa=' + date + '&bbb=xxx')"
**Instead of:** ('aaa=' + date + '&bbb=xxx')

:sos:

**Comment by HoudaDabou** [comment]
I see :disappointed: 

I'll ask @vincent-psarga  about that matter and get back to you ASAP...

**Comment by vincent-psarga** [comment]
Maybe you could use `= "aaa=${date}&bbb=xxx"`, using mustaches to get string interpolation ?

**Comment by ylacaute** [comment]
Thanks you, that is working !
I tried many things like that but as I would never refresh the test-run view before generating code it was pointless :sweat_smile:
