### ISSUE TITLE
Action Words no longer automatically suggested when drafting Test STeps

### ISSUE THREAD

**Issue by GraemeBrooke** [hiptest/hiptest-issue-tracker#206]
### Steps to reproduce
1. Start typing a word or words in a Test Step
2. Action Words that exist that match were listed as suggestion
3. This stopped occurring about an hour ago in any of my projects

### Expected behaviour
1. Start typing a word or words in a Test Step
2. Action Words that exist that match should be as suggestion as always has occurred

### Actual behaviour
1. Start typing a word or words in a Test Step
2. Action Words that exist that match were listed as suggestion
3. This stopped occurring about an hour ago in any of my projects

### My configuration
**Chrome:**

**Operating system:**

**Comment by GraemeBrooke** [comment]
If you go to Action Words and Search one - although it is present, it is not found.  Additionally, Tags are doing the same - you typed part of a Tag title & any matching were listed to choose from - none are offered - this has all started since around 11am UK time today

**Comment by HoudaDabou** [comment]
Hi @GraemeBrooke!

As mentioned on that [tweet](https://twitter.com/Advoftractorboy/status/1197886157679407105), this issue is no longer topical.

Anyway thanks for your patience!
