### ISSUE TITLE
Jira connection failed from Chrome Version 54.0.2840.98 (64-bit)

### ISSUE THREAD

**Issue by npapastefanakis** [hiptest/hiptest-issue-tracker#21]
Hello,

When I am trying to connect my scenario with a Jira issue, the screen in Jira doesn't display the test runs and gives me a "you need to login to hiptest kind of message => 

![image](https://cloud.githubusercontent.com/assets/6351024/20676321/077f067e-b598-11e6-9871-1bcccbb13306.png)

At the same browser I am already logged in hiptest in another tab and if I click refresh in Jira the message remains the same. I tried the same scenario using incognito chrome session with no success.

Firefox the same scenario works as expected.

![image](https://cloud.githubusercontent.com/assets/6351024/20676372/35d0848a-b598-11e6-8592-592a8ba5b716.png)

Could you please advise?

**Comment by cbliard** [comment]
It looks like the session is corrupted. Can you try deleting your Chrome history:

1. On your browser toolbar, click the More (three vertical dots).
2. Point to **More tools**, and then click **Clear browsing data**.
3. In the "Clear browsing data" box, click the checkbox for **Cookies and other site and plug-in data**.
4. Use the menu at the top to select the amount of data that you want to delete. Choose **beginning of time** to delete everything.
5. Click **Clear browsing data**.

Then sign in again and all should work as expected.

**Comment by npapastefanakis** [comment]
No success. I tried also the incognito which doesn't use any cached data and nothing.

When I click on "3. Click here to refresh the page after login" on hiptest section here is the screen I have and the console output:

![image](https://cloud.githubusercontent.com/assets/6351024/20681672/45f07ca2-b5ad-11e6-831e-5b1af71b70aa.png)

**Comment by npapastefanakis** [comment]
For some reason the browser was blocking cookies from atlasian.com and hiptest.net while in jira domain

Resolution: go to chrome://settings/content and click on content settings => manage exceptions and add the following domains to allow cookies:

![image](https://cloud.githubusercontent.com/assets/6351024/20704471/09b6004c-b628-11e6-84a3-bc59aa9e8e33.png)

**Comment by cbliard** [comment]
Great! I was trying to reproduce your issue without any success. Thank you for taking the time to investigate 👍.

**Comment by npapastefanakis** [comment]
Thanks for your time!
