### ISSUE TITLE
Error during hiptest-publisher install on w10 workstation

### ISSUE THREAD

**Issue by micwic** [hiptest/hiptest-issue-tracker#210]
### Steps to reproduce
1. gem install hiptest-publisher
2.
3.

### Expected behaviour
hiptest-publisher is installed

### Actual behaviour
ERROR:  Error installing hiptest-publisher:
        The last version of nokogiri (~> 1.8, < 1.10) to support your Ruby & RubyGems was 1.9.1. Try installing it with `gem install nokogiri -v 1.9.1` and then running the current command again
        nokogiri requires Ruby version >= 2.2, < 2.6. The current ruby version is 2.6.5.114.

C:\Users\miche>gem install nokogiri -v 1.9.1
ERROR:  Error installing nokogiri:
        The last version of nokogiri (= 1.9.1) to support your Ruby & RubyGems was 1.9.1. Try installing it with `gem install nokogiri -v 1.9.1`
        nokogiri requires Ruby version >= 2.2, < 2.6. The current ruby version is 2.6.5.114.

### My configuration
N/A

**Operating system:**
W10 Professional 2004 19033.1

**Comment by HoudaDabou** [comment]
Hi,

Can you please take a look of that [hiptest-publisher issue](https://github.com/hiptest/hiptest-publisher/issues/167)?

The problem is similar to yours :)

**Comment by micwic** [comment]
Hello Houda, thanks answering.
Yes the problem is similar. I just installed hiptest-publisher by using ruby installer this early morning. I didn’t work. I reinstalled just yet, It works and I see 2.0.0 version installed by now. Thanks.

Cordiales salutations / mit freundlichen Grüssen / Kind regards

[cid:image001.png@01D5A8FE.E4CFA270]
Michel Wicky
Administrateur
Senior Consultant

Mobile: +41 79 414 94 44
Email: michel.wicky@osima.ch

Ruelle de Chaucery 2
CH-1807 Blonay


[Titre : LinkedIn - Description : image of LinkedIn icon]<http://www.linkedin.com/in/michelwicky>



De : HoudaDabou <notifications@github.com>
Envoyé : lundi, 2 décembre 2019 10:39
À : hiptest/hiptest-issue-tracker <hiptest-issue-tracker@noreply.github.com>
Cc : Michel Wicky <michel.wicky@osima.ch>; Author <author@noreply.github.com>
Objet : Re: [hiptest/hiptest-issue-tracker] Error during hiptest-publisher install on w10 workstation (#210)


Hi,

Can you please take a look of that hiptest-publisher issue<https://github.com/hiptest/hiptest-publisher/issues/167>?

The problem is similar to yours :)

**Comment by HoudaDabou** [comment]
Great! 

Thanks for letting us know :slightly_smiling_face:
