### ISSUE TITLE
Unable to import scenarios from feature files

### ISSUE THREAD

**Issue by ehtesham1981** [hiptest/hiptest-issue-tracker#211]
I am unable to import scenarios from feature file as its menu is no longer appearing in the menu bar. Please help
 
### Steps to reproduce
1. Login to Hiptest
2. Go to Scenarios
3. Click on dot menu

### Expected behaviour
Import from feature file option should be available in the menu

### Actual behaviour
Import option is no longer visible

![image](https://user-images.githubusercontent.com/26733786/69935945-2b5a3b00-14f8-11ea-8329-344df7e6a199.png)

### My configuration
**Browser:**Chrome 78

**Operating system:** Windows 8.1

**Comment by HoudaDabou** [comment]
Hi,

This is certainly due of your kind of plan, if you're benefiting from a Lite pack or the free version => you don't have access to the create/update/download of feature files option.

Does that answer your question?

**Comment by ehtesham1981** [comment]
Thanks @HoudaDabou 

Actually, in the licensing section Hiptest team did not mention that there would be some limitations on features rather they mentioned that so long the no. of collaborators is 3 or less, it will be a free plan.

**Comment by HoudaDabou** [comment]
That's correct, we must make some information more clearly :slightly_smiling_face: 

Thanks for the feedback!
