### ISSUE TITLE
Enhancement: Clone datatable

### ISSUE THREAD

**Issue by npapastefanakis** [hiptest/hiptest-issue-tracker#22]
I am trying to write some test cases where for most of them the Datatables used are similar. Is it a good idea to be able to clone an existing Datatable from another scenario to the one I am creating just to avoid typing all the inputs again and again?

**Comment by jracenet** [comment]
Hi @npapastefanakis!
This feature is already planned, as you can see in our public backlog: https://trello.com/c/ADGXzIdd/79-copy-paste-datatable-across-mutiple-scenarios

Don't hesitate to up vote it! We take the count of votes in consideration when prioritizing our developments :)

Thanks for the feedback!

**Comment by jracenet** [comment]
Hey @npapastefanakis 
Good news, the raw edition of a datatable is now allowed.
You can now copy and paste the content of a datatable in your Hiptest scenarios.

Happy testing!
