### ISSUE TITLE
Test run results overlap after scrolling

### ISSUE THREAD

**Issue by adamlacoste** [hiptest/hiptest-issue-tracker#24]
When viewing results for a test run, after expanding several collapsible lines and scrolling up and down a few times, the text ends up jumbled together, overlapping and becoming unreadable.

![hiptest_test_run_overlap](https://cloud.githubusercontent.com/assets/914072/21029350/e9b242ae-bd5e-11e6-9129-af380c23f5d1.png)

I can also provide an MP4 video demonstrating the problem, but this interface doesn't support the file type so please suggest the preferred way to hand over the file if desired.

**Comment by jracenet** [comment]
This issue has been fixed
