### ISSUE TITLE
Use Hiptest user as reporter in JIRA

### ISSUE THREAD

**Issue by frsta** [hiptest/hiptest-issue-tracker#25]
When I register and issue in JIRA from Hiptest I would like to use the Hitest user as reporter or be able to set the reporter in the configuration page.

**Comment by aurelien-reeves** [comment]
Hi,

This feature is planned, as you can see in our public Trello board: https://trello.com/c/WwMxpoUm/318-when-creating-a-jira-issue-use-the-real-user-name-as-author-not-hiptest-plugin

Don't hesitate to up vote it! We take the count of votes in consideration when prioritizing our developments :)

Thanks for the feedback!
