### ISSUE TITLE
Feature file for subfolder has syntax error

### ISSUE THREAD

**Issue by tim-littlefair** [hiptest/hiptest-issue-tracker#26]
We have a project in which we have a folder hierarchy in which one folder represents a general capability of our system and this has subfolders which reflect specific aspects of the capability implementation.
We have scenarios defined at both the upper and lower folder level, the Cucumber scenario file at the upper level generates correctly, but the one at the lower level generates with the "Feature: " content on the same line as the tag for the overall feature.
Further details about this issue will be emailed to the developers.

**Comment by vincent-psarga** [comment]
Hi Tim,

This sound weird. Can you send us the exported feature file so we can have a look at it and fix that in Hiptest publisher ?

Thanks,
Vincent

**Comment by vincent-psarga** [comment]
This has been fixed in hiptest-publisher 0.21.1
Thanks for the feedback :)<
