### ISSUE TITLE
Feature request: Post attachments with Test Run results

### ISSUE THREAD

**Issue by adamlacoste** [hiptest/hiptest-issue-tracker#27]
When I push my test results up to HipTest (as TAP, currently), I can see a button on the test run scenario result screen to add an attachment.  I would like to be able to post attachments (e.g. screenshots of failures) along with my results so that HipTest can be the sole repository of test data for my application.

**Comment by aurelien-reeves** [comment]
Hi @adamlacoste,

Sorry for the delay in the response.

That sound like a good idea - I'll submit it to the team during our next product meeting.

If I understood well the idea would be to submit attachements to test results programmatically, e.g. through an API entry-point?

**Comment by adamlacoste** [comment]
Correct.  I have been using hiptest.net/import_test_results/<id>/tap to post my results.  I would like to be able to associate these attachments with a specific test run and if possible, test UID as well.

**Comment by HoudaDabou** [comment]
Hi there,

Our team has added a feature request to allow GET/POST/DELETE attachments through the API in our backlog. 

You can find the related Trello card [here](https://trello.com/c/zrGfdkHF), please upvote for it to increase its priority in our production.

Thanks in advance for your vote.

Regards,
Houda
