### ISSUE TITLE
Feature request: Download attachments with scenarios

### ISSUE THREAD

**Issue by adamlacoste** [hiptest/hiptest-issue-tracker#28]
HipTest allows you to add file attachments to a scenario, but those attachments are not retrieved when I download my scenarios.  (I am using the HipTest Publisher SAAS interface, if that matters.)  I would like to be able to retrieve these files with my scenarios, as they can be relevant to the execution of those tests.

**Comment by aurelien-reeves** [comment]
Hi,

Sorry for the delay of the response.

That sound legitimate, I'll submit the idea to the team during our next product meeting.

Sorry for your feedback!

**Comment by HoudaDabou** [comment]
Hi there,

HipTest team has added this feature request in the roadmap, you can find [here](https://trello.com/c/LiOeyw8A) the related Trello card.

Please upvote for it to increase its priority in our production.

Thanks in advance for your vote.

Houda
