### ISSUE TITLE
Feature request: Test Run results for multiple cases

### ISSUE THREAD

**Issue by adamlacoste** [hiptest/hiptest-issue-tracker#29]
Currently I am executing browsers tests in firefox and chrome.  The same test needs to be run in both.  However, I cannot post separate results for each of these tests to HipTest without one overwriting the other, because they have the same UID.  As a temporary solution I am compositing these results, so the test is considered to have passed if it passed in both browsers, and not otherwise.

We are now looking at expanding to more browsers and platforms such as Safari and mobile.  This temporary solution will not hold up well.  If possible, it would be great to be able to post multiple results for the same test under different conditions.

**Comment by vincent-psarga** [comment]
Hi Adam,

Our idea for this kind of problems is to add the possibility to handle group of test runs. To explain briefly, a group of test run will me managed as a single test run (for example, if you add a scenario to a group it will add the scenario to all test runs in the group etc) and will allow to handle execution on several platforms.

The Trello task for this can be found here: https://trello.com/c/kpTJ8H5z/119-i-want-to-execute-the-same-test-on-different-platform-environment-with-different-results

**Comment by adamlacoste** [comment]
Any new developments on this feature?  I haven't seen the Trello task move at all.

**Comment by HoudaDabou** [comment]
Hi @adamlacoste,

The development of the multiple execution environment is a work in progress, as you can see on our Trello board [here](https://trello.com/c/kpTJ8H5z). 

This feature should be released in the following month, feel free to follow its progress from our backlog.

Regards,
