### ISSUE TITLE
Test Run results not ordered same as Scenarios section

### ISSUE THREAD

**Issue by adamlacoste** [hiptest/hiptest-issue-tracker#30]
Test results in the Test Runs section of the HipTest app do not sort in the same order as they appear in the Scenarios section.  In order for me to maintain the correct order, I need to prefix the test names with a number, which makes it a hassle to renumber the whole list if I add something new.  Please respect the manual sorting from Scenarios under Test Runs as well.

**Comment by severinedarlot** [comment]
Hello Adam,

you do not need to prefix the test names. In the test run, the same order is used. If you click on the folder in the test run, you will find the scenarios in the same order. 

![selection_019](https://cloud.githubusercontent.com/assets/1829919/24506506/085c8686-155e-11e7-816e-38af7be8eda5.png)

BUT there 2 places where the scenarios are displayed in the alphabetic order :

- on the test run page (that allows to filter scenarios by status)
- in the scenarios list
![selection_018](https://cloud.githubusercontent.com/assets/1829919/24506526/19f9f04a-155e-11e7-8e99-52ff71e34761.png)

I hope this helps you.
