### ISSUE TITLE
Attachments in Scenarios are not displaying in Test run

### ISSUE THREAD

**Issue by selgonda** [hiptest/hiptest-issue-tracker#32]
If a Scenario with an attachment(screen shot) is added to a Test run, the attachment is not there to view in the Test Run. 
Probably when a Scenario is added to a test run the attachment is not carried over.

**Comment by jracenet** [comment]
Hi @selgonda 
The attachments are indeed not carried over when a scenario is added to a test run.
It's something we have already planned to work on, as you can see in our public backlog:

https://trello.com/c/lAR9Tlkv/269-carry-over-attachments-when-creating-a-test-run

Thank you for the feedback :-)
