### ISSUE TITLE
Unable to fill the required "assignee" field

### ISSUE THREAD

**Issue by Pierrehb** [hiptest/hiptest-issue-tracker#33]
Hello, 

I can't go through this issue. 
I try to create a JIRA from Hiptest and am asked to fill the assignee as it is a mandatory field. 

I've been trying different formats : userID in JIRA, userName in JIRA, userMail in JIRA. 
None worked. 

What am I supposed to use ? 

Thank you ! :)

**Comment by aurelien-reeves** [comment]
Hi,

May I ask you to contact the support using the in-app chat, or at support@hiptest.net, to discuss about your Jira setup?

Regards,
Aurélien
