### ISSUE TITLE
Question : How do you unlink a Project from an unsubmitted Organization ?

### ISSUE THREAD

**Issue by fjanes-at-amadeus-dot-com** [hiptest/hiptest-issue-tracker#36]
QA Note
On Create, an Organization can be linked to a pre-existing Project.
However, once linked, I don't see a way to 'unlink' a Project from an (unsubmitted) Organization ?

**Comment by jracenet** [comment]
Hello,
A project is always linked to an organization.
If you need to link your project to an other organization, you can achieve that from the project settings page. You will need to be an administrator of the project.

I hope it answers to your question :)

**Comment by fjanes-at-amadeus-dot-com** [comment]
Hi,
If I create an Organization first, and subsequently create a Project, the Project appears to be linked to an Organization, yes.

However, if I create a Project first, and then subsequently create an Organization, without selecting a Project, the Project exists unlinked to the Organization.
I can subsequently select to link the Project to an Organization,
so I was assuming you could also unlink the Project from an Organization ?

**Comment by aurelien-reeves** [comment]
Hi,

Indeed once you create an organization you are no more allowed to create new project that are not linked to organization.

Old projects remains not attach to organization but that will be the only projects you'll see not linked to organization. You actually won't be able to unlink a project from an organization. This is the desired behavior.

Fortunately on the cloud edition you still can move out a project from an organization, say for example for side projects. To do so just create an organization of your own - be sure to keep it under 3 users to not be charged for it afterwards - then as an administrator of your projects you'll be able to move them from an organization to the other one.
