### ISSUE TITLE
Feature request: inherit setup

### ISSUE THREAD

**Issue by nmaris** [hiptest/hiptest-issue-tracker#37]
If the setup of a folder of scenarios generates first the setup of the upper folder, it will enable us to put a setup at folders that have subfolders

**Comment by severinedarlot** [comment]
Hello, this feature seems to be already in the Hiptest backlog: https://trello.com/c/onmYJJ1U/317-option-propagate-setup-section-on-subfolders, but not yet planned.
You can vote for it :-)

**Comment by nmaris** [comment]
We'll track it from trello, thanks.
