### ISSUE TITLE
Feature request: sync and add scenarios

### ISSUE THREAD

**Issue by nmaris** [hiptest/hiptest-issue-tracker#38]
For a BDD workflow, we need to automatically do the following whenever a non-programmer edits hiptest:

1. synchronize
2. add new scenarios to test run

Is there any option or API call for that?

**Comment by jracenet** [comment]
Hey @nmaris,

You would like your test run to be automatically synchronized on the update of its features/scenarios, is that right?

We have added a task in our backlog to handle this case:
- [Automatically synchronize test runs](https://trello.com/c/vpfFxKmw/311-automatically-synchronize-test-runs)

I also added the "Synchronize" and "Add to test run" operations to be performed through our API in our public backlog:

- [Synchronize a test run](https://trello.com/c/38v7lMcd/363-api-synchronize-a-test-run)
- [Add scenarios to as test run](https://trello.com/c/Mw6pzaUS/389-api-add-scenarios-to-test-run)

Thanks for the feedback

**Comment by nmaris** [comment]
Yes, just 'Automatically synchronize test runs'.

If you provide 'Automatically synchronize test runs', then we don't need any API to 'Synchronize a test run' and 'Add scenarios to as test run'.

**Comment by HoudaDabou** [comment]
Hi @nmaris,

Feel free to upvote for [this feature request](https://trello.com/c/vpfFxKmw) in our backlog to increase its priority in our production and follow its progress :)

Thanks in advance for your vote.
