### ISSUE TITLE
Don't duplicate Gherkin keywords in Action Word phrases

### ISSUE THREAD

**Issue by adamlacoste** [hiptest/hiptest-issue-tracker#39]
If I write an Action Word this way...

<img width="535" alt="screen shot 2017-09-20 at 12 26 18 pm" src="https://user-images.githubusercontent.com/914072/30658434-43335fb6-9e00-11e7-85b2-efb2f85d501f.png">

And then start typing "Given that the" into a scenario step field, I get that action word as an autocomplete suggestion.

<img width="436" alt="screen shot 2017-09-20 at 12 27 11 pm" src="https://user-images.githubusercontent.com/914072/30658438-46281a36-9e00-11e7-9458-26ab5d999203.png">

But if I then click it, the step that appears in the scenario duplicates the Gherkin keyword "Given", looking like this:

<img width="391" alt="screen shot 2017-09-20 at 12 27 18 pm" src="https://user-images.githubusercontent.com/914072/30658446-48d8b538-9e00-11e7-868b-3b1fdb88d045.png">

The only way to avoid that problem is to omit Gherkin keywords from the Action Word phrases I create.  But this creates its own problems, because without those keywords it becomes difficult for people writing scenarios to understand which Action Words that autocomplete suggests to them are meant to be given, when or then.  And these distinctions matter, because I am constantly finding scenarios written where a "when" action word is being used as a "then", and when parsed by cucumber the resulting behavior will not be correct (taking an action instead of expecting a result).

Here are my suggestions for how this should work:

If I create an Action word that begins with "Given", "When", or "Then", that word should not be doubled up in the scenario step editor.  If I click the given/when/then keyword, I should be able to replace it in the scenario step editor with "And" or "But", but not any of the other keywords.  When I type "Given that the" into a blank step field, autocomplete should not suggest any steps that begin with "when" or "then".  This way, an Action Word that includes "Given", "When" or "Then" can enforce its type when used in scenarios.

**Comment by jracenet** [comment]
Hi @adamlacoste,

Thank you for the feedback!

Indeed, it can be difficult with the step suggestion to find out which action word is supposed to be used with  given or then (and so on).

I personally like the way you see the implementation of it :)
We will talk about this at our next product meeting to plan it, and challenge solutions for the best experience possible.

Best regards

**Comment by HoudaDabou** [comment]
Hi @adamlacoste,

Maybe you noticed it, but this issue was fixed.

Thanks again for your feedback :) 

Regards,
Houda
