### ISSUE TITLE
Not able to invite user to existing project getting error " User xxxx@gmail.com not found "

### ISSUE THREAD

**Issue by vikramvi** [hiptest/hiptest-issue-tracker#4]
Tried to invite user to existing project and got this error

https://hiptest.net/app#/projects/16871/settings

Please find console log

POST 
XHR 
https://hiptest.net/projects/16871/timeline [HTTP/1.1 400 Bad Request 56ms]
no element found

**Comment by vincent-psarga** [comment]
Hi,

That's "normal" (but something we have to improve to make it clearer). If a user does not exist in the system, you can not add him to a project.
That said, what you can do is:
 - go to your organization and invite the user there (that will send him an email to register on Hiptest)
 - go back to the project and add him there (once invited, the user email is known)

When he'll accept the invitation, he'll belong to your organization and have access to the project.

Best regards,
Vincent

**Comment by vincent-psarga** [comment]
We'll close that issue once we got some clearer process :)

**Comment by vikramvi** [comment]
In this case user scenario will be add / remove user from your organization on project Settings page , instead of invite flow.

**Comment by aurelien-reeves** [comment]
The error message displayed on the project settings page has been updated to be more comprehensive.
