### ISSUE TITLE
Don't allow editing Action Words from the Scenario editor

### ISSUE THREAD

**Issue by adamlacoste** [hiptest/hiptest-issue-tracker#40]
Currently, when viewing the Scenario editor screen, if I mouse over a step, it highlights like a link.  Clicking this "link" causes it to be converted into a text field, allowing me to edit the wording.  What is *not at all* clear here is that I am editing the underlying Action Word, not just for this scenario but *everywhere it is used*.

This can have inadvertent and widespread effects on a test suite, particularly if these steps need to be phrased a particular way in order to parse (e.g. in Cucumber).  It is just way too easy to break the whole suite this way.

Possible fixes:
1. Disable this feature (clicking the step link takes you to the Action Word screen, it doesn't let you edit in place)
2. Allow modifying Action Words from the scenario editor, but create a new Action Word for the new wording so that other scenarios aren't affected
3. In combination with either of the previous two options, you could have a toggle in the settings to switch between the current behavior and the more cautious approach I am recommending.

**Comment by jracenet** [comment]
Hi @adamlacoste,

We have a couple of users that have encountered this issue in the scenario design, and we apologies for it :(

We don't want to disable this feature. A far more lot of people were complaining about the non-possibility to edit an action word step directly in scenario definition (it's a bit tedious to navigate to the action word, edit the name, go back to the scenario)

The solution we've thought about is closest from your fix number 2, except that we want to let the choice to the user of the behaviour they prefer after the edit (either "Rename everywhere" or "Rename only here", that will create a new action word)

Thank you for the feedback :-)

**Comment by jracenet** [comment]
Hey @adamlacoste 

I'm happy to announce you that we have deployed our new inline action word edition feature:
![new_aw_editor](https://user-images.githubusercontent.com/3470258/32603583-8b6f9b3e-c54a-11e7-9d49-11bd124ce81d.gif)

So now, you'll have the choice to rename the step/action word only in your current scenario or in every places (scenario or action word) where it is used/

I hope you'll like it :)

**Comment by adamlacoste** [comment]
This is a big improvement, thanks very much!
