### ISSUE TITLE
Error message "Something bad had happened..."

### ISSUE THREAD

**Issue by NatalijaRokina** [hiptest/hiptest-issue-tracker#41]
Hello!
Please help with the issue attached
![error_hiptest](https://user-images.githubusercontent.com/32734168/31490372-5e605e9e-af4c-11e7-8cec-f2d656869ca1.png)

Thank you in advance.
Natalija

**Comment by karamosky** [comment]
Hello @NatalijaRokina 
We were experiencing server slowness this morning, Hiptest is now back to normal.
Can you confirm if it works for you ?
Thanks

**Comment by NatalijaRokina** [comment]
Thank you - everything is ok now!
