### ISSUE TITLE
Scenario Edit mode, clicking on wrench icon changes to eye icon & vice versa ( UX )

### ISSUE THREAD

**Issue by vikramvi** [hiptest/hiptest-issue-tracker#45]
![wrench-eye-icon](https://user-images.githubusercontent.com/308490/31671327-0362a6f2-b35a-11e7-9d01-a5c088973b6d.png)

- Refer to attached screen shot
- User is in scenario edit mode
- user clicks on wrench icon
- Wrench icon changes to eye icon

Actual Result:
1. this is confusing flow, as it's not obvious what this eye icon suppose to do or mean ?

**Comment by cbliard** [comment]
Clicking on this icon will switch a step between action and result. Is it a step that should be executed or checked?

It's true that it needs some UX love. Thanks for reporting that.

**Comment by HoudaDabou** [comment]
Hi again @vikramvi,

As you can see, with the new HipTest design you only have to press "View tests" from a scenario to see its result =)

Thanks again for your feedback!
