### ISSUE TITLE
Test Execution Report Navigation is backwards

### ISSUE THREAD

**Issue by vikramvi** [hiptest/hiptest-issue-tracker#46]
![navigation_backwards](https://user-images.githubusercontent.com/308490/31671634-acffc37a-b35a-11e7-99f0-7521047613a8.png)

- refer to attached screen shot
- user is at top most user story
- check the top right for navigation icon

Actual Result:
1. Navigation icon is backwards

Expected Result:
1. Navigation icon should be forward, as user has started from top most user scenario

**Comment by cbliard** [comment]
Hi,

In fact, in the "Tests" view, tests are ordered alphabetically, they are not ordered by their execution order. Execution order depends on which folder the test is in, the rank of the test within this folder and the rank of the folders themselves.

That being said, you are right: this view is very misleading and we will see what can be done for it.

Thank your for the report.

**Comment by HoudaDabou** [comment]
Hi there,

To date, tests are ordered by their execution order, thanks again for your suggestion!

Regards,
