### ISSUE TITLE
Improvement: After sending invite to an id , status should show pending till user join organization

### ISSUE THREAD

**Issue by vikramvi** [hiptest/hiptest-issue-tracker#5]
In Organization setting , after entering email id and completing invite action , I don't see if the user has accepted invite or not.

It will be nice to have below options

1. Pending
2. Accepted / onboard
3. Resend ( in case user has not accepted )
4. Show email id instead of showing name under User column , as while inviting I might have entered wrong email id.
5. Invitation date ( I can track how old was the invite and take action accordingly )

Please review

**Comment by vincent-psarga** [comment]
That sounds good. Maybe not all those informations in the users panel (as we plan to add some more informations later on), but the critical ones in the users panel and one dedicated to the pending invitations, showing all the information you listed here.

We'll discuss that at the next product meeting :)

**Comment by vikramvi** [comment]
Thanks @vincent-psarga

**Comment by vincent-psarga** [comment]
Hi @vikramvi,

Your suggestion has been integrated to Hiptest. Feel free to add some remarks here about the new organisation/invitation panel.
I'll close the issue if what has been added matches what you expected :)

Best regards,
Vincent
