### ISSUE TITLE
Execution results status is wrong

### ISSUE THREAD

**Issue by vikramvi** [hiptest/hiptest-issue-tracker#50]
![execution_results_status_is_wrong](https://user-images.githubusercontent.com/308490/31673974-dc521172-b360-11e7-86cd-9121749c789d.png)

![executionstatus](https://user-images.githubusercontent.com/308490/31673980-e0a666a6-b360-11e7-9900-19473fa8ef62.png)

- refer to attachments
- user has already finished execution of all the scenario; but under "Active test runs"; status is shown as "Execution is running"

**Comment by cbliard** [comment]
Thank you for the report,

In the screenshot you sent, the execution is still open: I can see it because there is a "Resume" button. When the execution is closed, the button is "New execution".

It is possible to have an open execution even if all tests have a result because you may want to review it, change a result description or its status. You have to close it to finish execution. It is proposed at the end of the process once all tests have been assigned a status. Once closed, the text "Execution is running" is not displayed any more in the test runs list.

Does it make sense for you?

**Comment by vikramvi** [comment]
I find this flow confusing.

Issue 1:
I understood what you meant to say. But from tester's perspective it's confusing UX. 
After updating status of each of the tests; it's not very obvious that one needs to close execution cycle.

Issue 2:
I closed execution cycle explicitly but still in the Test runs dashboard; I can see status as "Execution is running". This overall flow is not pretty obvious and buggy

**Comment by vikramvi** [comment]
![execution_cycle_is_closed](https://user-images.githubusercontent.com/308490/31707910-dde43500-b3ed-11e7-8258-d5a3897f7736.png)

In this screenshot, at top right after closing execution; user is shown error message "Execution cycle is closed you can't modify". But there is "Start" button at top left which is confusing.

Once user has closed particular execution cycle; why s/he needs to re-start/start same one; s/he will start new one isn't it ?

**Comment by cbliard** [comment]
A user can start a new execution on the same test run to see and record if it still passes. Some users use always the same test run, they add new scenarios to it during a sprint and create new execution at the end of their sprints. Some other create a new test run for each of their sprint.

It all depends on the workflow you want to setup with Hiptest, we do not enforce one way or another.

Does it make sense for you?

It's true that the UX can be confusing, especially for new-comers. We will do a global review of the UX on this part in the coming weeks. Your feedback is precious to know which areas need the most attention.

**Comment by vikramvi** [comment]
Thanks for clarification, sure you can add this issue in UX review meeting and please let me know the outcome.

**Comment by HoudaDabou** [comment]
Hi @vikramvi,

Since then, our team has developed a new design and new features, feel free to discover them!

Regards,
