### ISSUE TITLE
https://hiptest.net/app/projects missing tool tip

### ISSUE THREAD

**Issue by vikramvi** [hiptest/hiptest-issue-tracker#51]
![projects_page_missing_tool_tip](https://user-images.githubusercontent.com/308490/31674177-6e3e2a12-b361-11e7-8d2d-6cc1c0e2d7ef.png)

Refer to attached screen shot
tool tips are missing for bottom left 3 icons ( bell, notification, question mark )

**Comment by cbliard** [comment]
Thank your for the report, we'll add some tooltips to describe what these icons mean.

**Comment by jracenet** [comment]
Tooltips have been added on these menus.
Just don't forget to refresh your browser :)

Thanks for the report!

**Comment by vikramvi** [comment]
@jracenet  Thanks for quick fix. Verified working
