### ISSUE TITLE
When clone scenario the app modify all fields in both scenarios

### ISSUE THREAD

**Issue by leandro-romero-olx** [hiptest/hiptest-issue-tracker#52]
![oct-17-2017 18-16-50](https://user-images.githubusercontent.com/30843542/31689906-6cf95f22-b367-11e7-9df1-9b015d28f50e.gif)

If you clone a scenario, and after modify one field, the app modify the field of the scenario cloned. 

Step to reproduce:
1) Create one scenario
2) Clone the scenario created
3) Modify the first step in scenario cloned
4) Go back to the first scenario created

Result: The scenario previous created was modified by the scenario cloned. 

Evidence: 
https://hiptest.net/app/projects/62229

**Comment by cbliard** [comment]
Thank you for your report.

In fact, this is a more general issue: when you edit a scenario and change an action word call, it actually renames the action word, impacting all scenarios using this action word. That's what you are observing after cloning a scenario and renaming a step as they are obviously sharing the same action words.

Some other customers have faced the same issue you are reporting and we are considering stoping renaming the action word in favor of creating a new one if the action word is shared with other scenarios.

Would that fix the issue for you?

**Comment by leandro-romero-olx** [comment]
Hi @cbliard , yes! This approach it's fine for me and I think it's more intuitive to other customers too. 

Do you know when implement it? 

Regards

Leandro

**Comment by cbliard** [comment]
We should start development in the coming weeks. You can expect it before the end of the month. Does it work for you?

**Comment by leandro-romero-olx** [comment]
Ok, songs good for me! Thanks @cbliard

**Comment by yael-lorenzo-olx** [comment]
IMO we could have a "checkbox" to apply an atomic change or update all references

**Comment by leandro-romero-olx** [comment]
Buenisimo! :)




QA Lead in Research & Development
OLX Inc.
Mobile AR: +54 1139340483
E-mail: leandro.romero@olx.com <jules.weijdema@olx.com>
www.olx.com <http://www.olx.com.ar/>
Free classifieds

**Comment by jracenet** [comment]
Hey @leandro-romero-olx !

I'm happy to announce you that we have deployed our new inline action word edition feature:
![new_aw_editor](https://user-images.githubusercontent.com/3470258/32598436-1588c0ae-c53a-11e7-9081-fa51a1432c75.gif)

So now, you'll have the choice to rename the step/action word only in your current scenario or in every places (scenario or action word) where it is used/

I hope you'll like it :)

**Comment by leandro-romero-olx** [comment]
Clap clap @jracenet Thanks for the support!

**Comment by jracenet** [comment]
You're welcome! I close this issue :)
