### ISSUE TITLE
Add new tag should have help icon against it

### ISSUE THREAD

**Issue by vikramvi** [hiptest/hiptest-issue-tracker#53]
![add_new_tag](https://user-images.githubusercontent.com/308490/31708704-177d90ca-b3f0-11e7-8199-e0cfa947aa9d.png)

- Refer to attachment
- Many users who are using hiptest first time; will find it confusing to understand what is "Add new tag"
- If we can add "?" against each of the controls; clicking on which should open a small pop-up explaining what it is will be of great help to new users of hiptest and BDD as well

**Comment by cbliard** [comment]
Thanks for reporting. We'll try to add some help somewhere.

**Comment by vikramvi** [comment]
can you please add label enhancement ?

**Comment by cbliard** [comment]
Sorry, I did not get it. What do you mean by label enhancement?

**Comment by vikramvi** [comment]
some of the ticket are assigned with "Label:Enhancement" .  Please refer to existing issues with this label.

**Comment by jracenet** [comment]
Hey @vikramvi,

A tooltip has been added on tags widgets (when the tag list of an element is empty)
![capture d ecran 2017-11-02 a 10 20 06](https://user-images.githubusercontent.com/3470258/32318445-9a55bb12-bfb7-11e7-8d84-eee376cccc0a.png)

We will also add it in the "Tags management" widget, available in the folders pages.

Is it ok for you?

**Comment by vikramvi** [comment]
![screenshot from 2017-11-02 11-00-26](https://user-images.githubusercontent.com/308490/32320119-10f54a6c-bfbd-11e7-9675-58c40dc2a9b4.png)

@jracenet please refer to above screen shot,  tooltip is not shown if one/more tags are already present.

It needs to be shown to the new user who is using this tool first time.

**Comment by jracenet** [comment]
Yes you're right, I will let it displayed even if there are already tags

**Comment by jracenet** [comment]
Hey,

The tooltip is now always displayed against each tags list widget (when they're editable, so it won't appear in scenarios or folders lists, for example)

**Comment by vikramvi** [comment]
verified fixed.
