### ISSUE TITLE
Title strings should start with CAPS

### ISSUE THREAD

**Issue by vikramvi** [hiptest/hiptest-issue-tracker#55]
Many pages of hiptest with multi string title name doesn't have 2nd or 3rd string starting with CAPS

Please fix this across all the pages of hiptest

e.g.
Project metrics -> Project Metrics

Create new chart -> Create New Chart etc

**Comment by cbliard** [comment]
About capitalization, we ought to be consistent. In all the application, we have the same style, which is the first letter of the first word is capital, the other are normal. We'll have to check some reference work on this and take a decision about if we need to change to title-style or switch to sentence-style.

The priority is low on this item. We have other exciting features we want to deliver.
