### ISSUE TITLE
User management flow is confusing

### ISSUE THREAD

**Issue by vikramvi** [hiptest/hiptest-issue-tracker#58]
![manage_users](https://user-images.githubusercontent.com/308490/31712527-a7b3a9e4-b3fb-11e7-8ed6-e9e011d936b0.png)
![organization_users_management](https://user-images.githubusercontent.com/308490/31712529-a80d192a-b3fb-11e7-9065-46a094a7837f.png)
![users_management](https://user-images.githubusercontent.com/308490/31712530-a827ab46-b3fb-11e7-8289-7442061c0a44.png)

- as hiptest user; it's confusing from where to add a new user to a team or project
- first way I tried is Project page right side Manage users button; but this is not a valid flow; not sure why ?
- Then after some search; I could goto Organizations page to invite a user.

Can we integrate these flows; it is quite confusing.

**Comment by cbliard** [comment]
Yes, this flow is indeed confusing. We are going to experiment with users and billing management this quarter, and this is something that we will definitely address!

**Comment by vikramvi** [comment]
Thanks for review comment
