### ISSUE TITLE
Is it possible to import features into an existing project? 

### ISSUE THREAD

**Issue by yael-lorenzo-olx** [hiptest/hiptest-issue-tracker#59]
Currently when I import I have to create new projects and later move scenarios arround them.

Thank you.

**Comment by jracenet** [comment]
Hello @yael-lorenzo-olx,

It's not possible for now, but -good news- we are going to work on it this very quarter!
(You can see the card in our Trello backlog here: https://trello.com/c/N9bu9OgE/154-import-and-update-bdd-feature-files-in-an-existing-project)

Stay tuned, this feature will be available in the coming weeks :-)

**Comment by jracenet** [comment]
@vikramvi You can indeed export your scenarios into executable scripts (and so automate and version them) with the [hiptest-publisher](https://github.com/hiptest/hiptest-publisher)

For the integration with Github repo, we actually will do it! We still need to have a global picture of this feature (and the way we integrate it within Hiptest).We should start work on this next year :)

**Comment by jracenet** [comment]
The import feature has been released indeed :-)
