### ISSUE TITLE
User management roles under a project is confusing

### ISSUE THREAD

**Issue by vikramvi** [hiptest/hiptest-issue-tracker#61]
### Steps to reproduce
1.  Goto particular project's user management page
    https://hiptest.net/app/projects/xxxxx/settings
2.  Try to add new user

### Expected behaviour
1. The roles are confusing to understand Member/ Tester/l Reader / Admin.
2. Some kind of help section against the role can be helpful

### Actual behaviour
3.  New user gets added with default role as Member.

### My configuration
**Browser:**
NA

**Operating system:**
NA

**Comment by jracenet** [comment]
Hey @vikramvi,

Agreed, it's indeed quite confusing. 
I am currently working on the project settings page, and I will integrate some help in the users management widget.

It should be integrated soon :)

**Comment by jracenet** [comment]
Hi @vikramvi,

We've added a tooltip in the project users management widget:

![user_management_tooltip](https://user-images.githubusercontent.com/3470258/31946524-533571f0-b8d2-11e7-88b6-43605b5eff1c.png)

Is this good for you?

**Comment by jracenet** [comment]
It has been fixed. I close this issue :-)

**Comment by vikramvi** [comment]
verified fixed. Thanks @jracenet
