### ISSUE TITLE
Filter by tags

### ISSUE THREAD

**Issue by yael-lorenzo-olx** [hiptest/hiptest-issue-tracker#63]
I would like to know if you are considering the filter by tags.

Currently if I want to list all the scenarios that are @smoketests only I cannot.

**Comment by FatimaEzzahraIdrissi** [comment]
Hello @yael-lorenzo-olx 

The filter by tags if already available. To get your scenarios list, you have to search with smoketests without the "@" character. We have also a planned card in our public Trello backlog which aims to enhance the filtering abilities, Please find here the link: https://trello.com/c/sprLqFkk/110-filtering-abilities
i invite you to vote :) 

Best regards,
Fatima
