### ISSUE TITLE
Folder view improve with scenario names as leaves

### ISSUE THREAD

**Issue by yael-lorenzo-olx** [hiptest/hiptest-issue-tracker#64]
On the right pane on top I see this

Header: Regression Testing >  Functional >  Android >  Login
Title: Login Post

And on left pane (folder view)
Regression Testing
    Functional
        Android
            Login

I would like to see all the scenarios in that folder, otherwhise I just have to jump with the arrow back and forth until I find what I need.

Regression Testing
    Functional
        Android
            Login
              - Login Post
              - Login Chat
              - Login Notification
              - Login My Network

**Comment by jracenet** [comment]
Hi @yael-lorenzo-olx,

We have experimented this way to present data in the living documentation feature:

![ld-navigation](https://user-images.githubusercontent.com/3470258/31950026-03852f8e-b8db-11e7-8efb-6a0d392a380a.png)

Only the scenarios of the current open folder are displayed here.

Is this what you suggest for the scenarios folder tree?

**Comment by yael-lorenzo-olx** [comment]
From this first screen I go to the first scenario

<img width="1437" alt="screen shot 2017-10-24 at 12 06 47 pm" src="https://user-images.githubusercontent.com/22622247/31951451-899bdb4e-b8b4-11e7-8640-1a9a1361f8fd.png">

Then when I am at this scenario I would like to see the others that are present under the same feature.

<img width="1440" alt="screen shot 2017-10-24 at 12 07 01 pm" src="https://user-images.githubusercontent.com/22622247/31951452-89c9ab96-b8b4-11e7-87cb-a317b16f4644.png">

**Comment by jracenet** [comment]
Ok, thank you @yael-lorenzo-olx !
That's indeed the same idea than what we've implemented in the living documentation table of content.
We will surely redesign the tree structure this way.

Thank you for the feedback
