### ISSUE TITLE
Feature Setup Visible on Scenarios

### ISSUE THREAD

**Issue by yael-lorenzo-olx** [hiptest/hiptest-issue-tracker#65]
Given I am at the Feature view and view the setup that is common for all the scenarios

[
![screen shot 2017-10-26 at 5 18 17 pm](https://user-images.githubusercontent.com/22622247/32075312-d45979e2-ba72-11e7-84fc-a640c97b1ac4.png)
](url)

I would like to see this setup (non edit is ok) on each scenario edit mode

![screen shot 2017-10-26 at 5 18 35 pm](https://user-images.githubusercontent.com/22622247/32075360-f9a5b6fc-ba72-11e7-9e38-157d895adc62.png)

**Comment by jracenet** [comment]
Hi @yael-lorenzo-olx ,

Absolutely agreed! We have already planned to do so :-)
We will let you know when it's done!

**Comment by jracenet** [comment]
Hey @yael-lorenzo-olx !

The folder setup is now visible from the scenario page:
<img width="818" alt="capture d ecran 2017-11-07 a 11 19 20" src="https://user-images.githubusercontent.com/3470258/32488620-97c4c5d8-c3ad-11e7-96b2-e2783ff06145.png">

I hope you will like it :-)
