### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by shawny2005** [hiptest/hiptest-issue-tracker#66]
### Steps to reproduce
1.go to mobile (iPhone)
2.try to use hiptest
3.

### Expected behaviour
It should work, but it doesn’t.  No mobile views. I at least want to be able to run tests from mobile

### My configuration
**Browser:**iphone 7, safari

**Operating system:**

**Comment by jracenet** [comment]
Hey @shawny2005,
Indeed, we've never work on making the Hiptest GUI mobile-compliant.

Though, we have planned to release a mobile-app (for iOS and Android) for the test execution, as you suggested.

We will communicate about it as soon as we have a first beta version of the app (which is not in our short-term plans)

Thanks for your feedback
