### ISSUE TITLE
Cannot install hiptest -> jira cloud add-on

### ISSUE THREAD

**Issue by angellmedici** [hiptest/hiptest-issue-tracker#67]
### Steps to reproduce
1. Create new JIRA cloud instance  (new design)
2. Install Hiptest add-on inside the JIRA add-ons page
3. Click "Accept and Install"

### Expected behaviour
Add-on is installed

### Actual behaviour
Modal disappears.  Hiptest add-on is not installed.
No console errors.

### My configuration
**Browser:**
Chrome (latest)

**Operating system:**
MacOS

**Comment by vincent-psarga** [comment]
Thanks for the report, we'll have a look into the issue.

**Comment by vincent-psarga** [comment]
Hi,

I've just created a new Jira cloud instance and I did not get any issue when installing the plug-in. I apparently used the new version of Jira (with the nice blue left menu).
Is there any other inputs you can give me to reproduce your issue ?

**Comment by angellmedici** [comment]
> The add-on host returned HTTP response code 403 when we tried to contact it during installation. Please try again later or contact the add-on vendor.


![dec-05-2017 14-40-09](https://user-images.githubusercontent.com/33638107/33629601-45ce11a2-d9ca-11e7-810d-f5fc2f7c59d4.gif)

**Comment by angellmedici** [comment]
Still having this problem.  It'd be nice to get it fixed so we can attach bugs to our tests!

**Comment by aurelien-reeves** [comment]
Hi,

I think your issue has been solved with the support several days ago. Can you confirm?

**Comment by angellmedici** [comment]
Yes

*Angell Tsang*
<https://medici.md/>
Austin  |  Houston  |  Paris | Johannesburg

<http://medici.md/>   <https://www.facebook.com/medici.md/?fref=ts>
<https://twitter.com/medici_app>
<https://www.linkedin.com/company/medici.md>
Download Medici <https://www.medici.md/get-medici/>

On January 25, 2018 at 8:59:17 AM, Aurélien Reeves (notifications@github.com)
wrote:

Hi,

I think your issue has been solved with the support several days ago. Can
you confirm?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/hiptest/hiptest-issue-tracker/issues/67#issuecomment-360491077>,
or mute the thread

**Comment by cbliard** [comment]
Great! I'm closing this one.
