### ISSUE TITLE
Repeated parametrized action words

### ISSUE THREAD

**Issue by yael-lorenzo-olx** [hiptest/hiptest-issue-tracker#68]
Hello,

I found this issue today
![screen shot 2017-11-16 at 10 46 04 am](https://user-images.githubusercontent.com/22622247/32894480-b01b83fa-cabb-11e7-8869-a41cdc299764.png)

and I am not sure if it is a bug or not, as the parameter name is different. In this case the usage is the same everywhere with different parameter names which leads to duplicated action words with no value for the BDD approach. (IMO)

**Comment by jracenet** [comment]
Hey @yael-lorenzo-olx,

It's indeed a bug!

Could you:
- Give us some details about operations that may have caused this action word duplicate (scenario clone, imports, inline editing of an action word from a scenario definition). It would greatly help us :)

- Open your project to our support account so we can take a look at it and investigate?

By advance, thank you :)

**Comment by yael-lorenzo-olx** [comment]
Hi @jracenet, I am sorry, I did not see the previous comment, only the closed situation.

As you mentioned, it was definitely after a clone.
