### ISSUE TITLE
Option to export selected tests as automation scripts - Improvement

### ISSUE THREAD

**Issue by fc-sanju** [hiptest/hiptest-issue-tracker#69]
Option to export selected tests as automation scripts 

### Steps to reproduce
1. Open Hiptest
2. Go to Automation tab
3. Select a automation tool to export and click on the link
 
### Expected behaviour
Hiptest should provide an option to select the tests the user wants to export as automation scripts

### Actual behaviour
Currently all tests are exported to the required automation script format

### My configuration
**Browser:**
Chrome
**Operating system:**
Mac

**Comment by aurelien-reeves** [comment]
Hi,

Actually the automation tab in Hiptest is much more for bootstrapping purpose than for continuously managing automation.

To go further with automation and fully manage the life-cycle of your tests we provide the command-line tool [hiptest-publisher](https://github.com/hiptest/hiptest-publisher).

Feel free to take a look on [our documentation](https://docs.hiptest.net/), we have a section dedicated to [automation](https://docs.hiptest.net/automate-your-tests/), and to [create executable scripts](https://docs.hiptest.net/create-executable-scripts/) using Hiptest-publisher.

You can also take a look on [our Youtube channel](https://www.youtube.com/channel/UCx8MFcFrl8tUbfrXSAPDnLw). The video [Live demo of test automation](https://www.youtube.com/watch?v=S1wM5ArSqGM) may interest you :)

**Comment by jracenet** [comment]
Hey @fc-sanju :)

We have improved the web interface of hiptest-publisher (which is accessible here: https://hiptest-publisher.scalingo.io/ and from the Automation panel in Hiptest).

You can now filter your tests directly from this interface in order to get only the tests you want :)

Hope it helps!
