### ISSUE TITLE
How to collaborate on user stories

### ISSUE THREAD

**Issue by vikramvi** [hiptest/hiptest-issue-tracker#7]
I am finding it difficult to understand , how to collaborate on user stories.

It will be nice if tool has below
1. revision history 
2. commenting on individual user stories like google doc

Please review

**Comment by aurelien-reeves** [comment]
A basic revision history has been added to Hiptest and it has been planned to be enhanced: https://trello.com/c/IlRvXMyM/268-revision-history-enable-to-retrieve-back-a-previous-version-of-a-scenario-action-word-for-undo

Commenting stories (folders, scenarios, tests) is also in our backlog: https://trello.com/c/S6XKihvC/214-i-want-to-comment-on-stories-folder-scenarios-tests

Thank you for your feedback, and feel free to up-vote those features in trello!
