### ISSUE TITLE
(Using Hiptest) Is there a way to show the Hiptest test cases in Jira ?

### ISSUE THREAD

**Issue by fc-sanju** [hiptest/hiptest-issue-tracker#70]
(Using Hiptest) Is there a way to show the Hiptest test cases in Jira ?
 
### Steps to reproduce
1. When I write a test in Hiptest
2. And I create a Jira ticket and link it
3. Then I should be able to see the written test case in Jira 

### Expected behaviour
I should be able to see the written test case in Jira 

### Actual behaviour
I do not see a way to see the test cases in Jira  
 
### My configuration
**Browser:**

**Operating system:**

**Comment by karamosky** [comment]
Hello @fc-sanju 
We actually have this feature request included in our backlog (see https://trello.com/c/TAoKuWxw/288-display-edit-test-steps-in-jira)
I recommend voting for it so we can raise it's priority :) 
Regards
