### ISSUE TITLE
Move Actionwords List to Test-Plan page as additional Tab : UX Improvement

### ISSUE THREAD

**Issue by kudinov-fedor** [hiptest/hiptest-issue-tracker#74]
### Expected behaviour
When I am on Test-Plan page and work with scenarios
I would like to see List of Actionwords and work with them (create, filter) on the same page 
(e.g. as additional tab  | Folders | Scenarios | Actionwords | )

![](http://storage7.static.itmages.com/i/17/1222/h_1513935672_2703509_59c4782d25.png)  

In future it will be great to make drag&drop mechanics for adding of Actionwords to scenario

### Actual behaviour
When I am on Test-Plan page and work with scenarios
I can`t see all my Actionwords and need to remember at least part of Actionword to use it in scenario

**Comment by jracenet** [comment]
Hey @kitway-m1y !

Good news, we will do this in the coming months!

We are indeed going to introduce a way to organize your action words by group and share them across multiple projects, and we were thinking about moving the action words management in the test plan itself :)

Thank you for your feedback, and stay tuned!
