### ISSUE TITLE
How can I move folders between projects. Currently I cant.

### ISSUE THREAD

**Issue by rajeshbtech009** [hiptest/hiptest-issue-tracker#75]
### Steps to reproduce
1. Create two projects
2. Create folders in project1
3. Now try to move the folder to project 2

### Expected behaviour
Move dropdown comes with all projects available in hiptest

### Actual behaviour
Currently it shows only the current project

### My configuration
**Chrome**

**Win 7**

**Comment by vincent-psarga** [comment]
Hi,

Indeed moving is limited to the current project. That said, you can use the clone button that will make a copy of those folders to the destination project and then delete them later on.

Best regards,
Vincent

**Comment by rajeshbtech009** [comment]
Ok Thanks
