### ISSUE TITLE
Bad performance while creating/moving subfolders and scenarios

### ISSUE THREAD

**Issue by mpernkopf** [hiptest/hiptest-issue-tracker#76]
I'm acutally facing a performance issue. When creating or moving subfolders and scenarios the time for saving takes at least 10 seconds. I got a lot of subfolders and scenarios (all together about 400; way more to come since this is only a base set of scenarios actually)) and it takes ages to save them.

Additional note: Meanwhile the bad performance occurs on every single task of renaming/creation/moving folders or scenarios.
 
### Steps to reproduce
1. Create Scenario
2. Create Subfolder
3. Move Scenario into Subfolder

### Expected behaviour
Saving/Moving scenarios and subfolders shouldn't take > 10sec

### Actual behaviour
Bad performance when creating subfolders and moving scenarios into subfolders (10 - 12 seconds per move, so appx. 2 minutes of waiting when moving aroung 10 scenarios)

### My configuration
**Browser:**
Chrome 63.0.3239.84

**Operating system:**
Windows 10

**Comment by mpernkopf** [comment]
Performance got better so I'll close this ticket again.

**Comment by karamosky** [comment]
Hello @mpernkopf ,
Thanks for reporting this issue, we are going to investigate, but could you please provide us with further informations.
Please send us an email at support@hiptest.net with the following:
- Your email
- The project where the issue has been occurred
Kind regards
Karam
