### ISSUE TITLE
Can't create scenario with non-unique name

### ISSUE THREAD

**Issue by JheeBz** [hiptest/hiptest-issue-tracker#78]
### Steps to reproduce
1. Create a project
2. Create a folder, let's call it "Area One"
3. Create a Scenario in the folder with a simple name like "Make sure that branding displays" (BDD convention)
4. Create another top-level folder called "Area Two"
5. Create a Scenario in the second folder with the same name "Make sure that branding displays"

### Expected behaviour
It should be possible to create multiple scenarios with the same name. I don't think a non-unique attribute like a name should be checked for uniqueness. Otherwise it'll create verbose scenario names like "Make sure that branding displays on Page A" while the tests may already be under a "Page A" directory.

### Actual behaviour
A scenario with name 'Make sure that branding displays' already exists and the scenario cannot be created.

### My configuration
**Browser:**
Chrome 63

**Operating system:**
Win 7 and Win 10

**Comment by vincent-psarga** [comment]
Hi,

This is something we plan to add to Hiptest: https://trello.com/c/WpxSfeYp/203-enable-to-have-same-names-for-scenarios-in-different-folders

To explain briefly why we do not allow that, that is some legacy coming from when Hiptest did not support folders to organize the tests (that was a loooong time ago :D ) and we still need to ensure we do not get any conflicts when generating the tests scripts as a single file.

**Comment by jracenet** [comment]
Closed since it is already in our backlog.

Thank you for the feedback!
