### ISSUE TITLE
Testrun is not added to project after creating, making test automation impossible

### ISSUE THREAD

**Issue by systemr82** [hiptest/hiptest-issue-tracker#79]
### Steps to reproduce
1. Create a new testrun for a project

### Expected behaviour
I would expect the new testrun to be added to my project so I can use the project number for test automation

### Actual behaviour
The testrun is not added to my project, and also not visible on the project dashboard and because of that I can not automate the tests since the project is not recognized when using the command: 
hiptest-publisher --config-file C:\gatautomationpoc\src\test\java\hiptest\hiptest-publisher.config --test-run-id 130729 --without=actionwords

### My configuration
**Browser:**
Chrome and Edge

**Operating system:**
Windows 10

**Comment by jracenet** [comment]
Hey @systemr82 ,

Could you send us by email (support@hiptest.net) the following information:

- The URL of your project
- Your hiptest-publisher config file

Our support team will investigate this issue ASAP

Thank you :)

**Comment by karamosky** [comment]
Hello @systemr82 
Any news for this issue ? 
Can you please tell if you still encounter this ?
If so can you please send us the informations needed so we can investigate ?
Thanks

**Comment by HoudaDabou** [comment]
Hi @systemr82,

Any update on this issue?

I close this one but feel free to contact our team by email (support@hiptest.com) to help you if you need.

Regards,
Houda
