### ISSUE TITLE
TestRun should be editable

### ISSUE THREAD

**Issue by luis-portillo-olx** [hiptest/hiptest-issue-tracker#81]
In order to perform a Test Suite managing, it would be a good idea make the Test Run editable. In order to add or remove scenarios according to Suite coverage requirements.

**Comment by TimotheeVille** [comment]
Hi,
This is possible directly from the test run section of the application. 
You can add tests from the test-run main page with the 'Add scenarios' button just below the test run name.
And to remove a test, just go to the concerned test in your test-run and click on the 'Remove from test run' button.

Tell me if it answers your question.
Regards.

**Comment by luis-portillo-olx** [comment]
Yes, I discovered the button. Thank you
I will close the issue
