### ISSUE TITLE
Add webinar and https://hug.hiptest.net/ links on home page

### ISSUE THREAD

**Issue by vikramvi** [hiptest/hiptest-issue-tracker#82]
### Steps to reproduce
1.  I wanted to share today's webinar link with one of my US based friends.
     But couldn't find it anywhere on your website.
2.  This critical link is hidden
3.

### Expected behaviour

1. Please add below critical links on home page
1.1. Webinar
1.2  blog
1.3 HUG https://hug.hiptest.net/

2.  This will help users to navigate to these critical links quickly

@laurentPy 

### Actual behaviour
NA

### My configuration
NA

**Comment by FatimaEzzahraIdrissi** [comment]
In the home page, we share one of the planned webinar and it's continuously updated. Today's webinar is available here : https://attendee.gotowebinar.com/register/7907983783137967874
The blog post is accessible from the home page:
![hiptest agile test management tool behavior driven development](https://user-images.githubusercontent.com/22891277/35864080-01c69d04-0b51-11e8-844f-6ca46951840c.png)
About Hug, we share it during the customer support. We'll work on the home page and these links will be more visible with all details.
Thank you for your feedback and sorry for the inconvenience!
Best regards,
Fatima

**Comment by vikramvi** [comment]
Thanks for answer it was just better UX suggestions.

What's about link to earlier webinars ?

IMHO there is lots of useful info which is hidden from homage page

**Comment by FatimaEzzahraIdrissi** [comment]
Here is the links of the 3 last webinars:

January 30: BDD with Hiptest
https://attendee.gotowebinar.com/register/8618264996146369282

February 1st : Automate your tests with Hiptest
https://attendee.gotowebinar.com/register/2612211316722297602

February 6 : - Agile test management with Hiptest
https://attendee.gotowebinar.com/register/7907983783137967874

Regards

**Comment by cbliard** [comment]
Hi,

Now on the new https://hiptest.com web site, it should be easier to find the [get stared page](https://hiptest.com/start/) with next webinars on it, as well as the [Hiptest community web site](https://community.hiptest.com/) (formerly known as HUG).

I'm closing this issue but feel free to reopen it if you need more explanations.
