### ISSUE TITLE
Allow step statuses to be updated via the API with the test results endpoint

### ISSUE THREAD

**Issue by adamlacoste** [hiptest/hiptest-issue-tracker#84]
It does not appear to be possible to set step statuses via the Test Run execution results endpoint of the API.  I would like to be able to do so to provide a detailed accounting of where, precisely, a scenario failed.  It is currently only possible to do this via the description field, which is rather clumsy.
 
### Steps to reproduce
1. Assign test execution results via the API, with the `data.attributes.step-statuses` property set to an array of valid status values (e.g. "passed") (https://hiptest.github.io/slate/?shell#assign-test-execution-results-to-a-build)

### Expected behaviour
The `data.attributes.step-statuses` property of the response JSON object should be set to an array matching the one submitted, and these statuses should appear in the HipTest UI for this scenario.

### Actual behaviour
The `data.attributes.step-statuses` property of the response JSON object is an empty array, and the HipTest UI lists the scenario's step statuses as "undefined".

**Comment by severinedarlot** [comment]
Hello Adam, 

Thank you for the suggestion. This feature has been added to the Hiptest backlog: https://trello.com/c/mbaKoOEB/417-api-update-the-status-of-a-step-result. You can vote for it.

Best regard
