### ISSUE TITLE
Case conversion in data table column headers

### ISSUE THREAD

**Issue by adamlacoste** [hiptest/hiptest-issue-tracker#9]
While creating data tables for some of my scenarios in HipTest, I used ALL CAPS column headers (e.g. `SITE_NAME`) so that the variable references which appear in the scenario steps would be easily distinguished visually (e.g. `= SITE_NAME`).  This is because some action word parameters in our steps end up as variable references and some are simply filled in with a static value for that scenario.

What I discovered when downloading an export of these scenarios in gherkin format, however, is that a case-conversion is performed on the data table column headers, making them lower case (`| site_name |`) while the variable references in the scenario steps remained upper case (`<SITE_NAME>`).  Cucumber.js is case-sensitive, so the variable reference is not understood.

I don't have much of an opinion either way on whether type conversion should or shouldn't take place.  I lean a little toward leaving things in the format that the user wrote it in, but if there's a technical reason to convert, that's fine with me.  It just needs to make that case conversion to the variable references as well, so they don't break.

EDIT: added code formatting to elements that were getting misinterpreted by editor.

**Comment by vincent-psarga** [comment]
Hi Adam,

Good news, that should be doable out of the box with hiptest-publisher override templates (you'll have to use hiptest-publisher instead of the SaaS version of course).

Could you provide me with an example of what is generated and what you expect as output so I can have a bit more information and guide you on how to customise the export ?

**Comment by vincent-psarga** [comment]
Damn I forgot you had issues with hiptest-publisher on your computer :/
I'll see if we can also enable overriden templates in the SaaS version of the publisher :)

**Comment by adamlacoste** [comment]
Don't worry about us, I just switched to using lower case data table headers and var references, to avoid the problem.  It's an easily circumvented bug.

But for the sake of addressing the bug, here's an example of what's going on.  In a particular scenario in HipTest, let's call it "Validate Nav", I have a data table which has a column named `SITE_NAME`.  Then in the scenario steps, there is a line that reads, `Given that I am on the "= SITE_NAME" "home" page`.  (Quoted areas are action word parameters.)

When I download my feature files using the SAAS interface, I get something that looks like this:

```
  Scenario Outline: Validate Nav
    Given that I am on the "<SITE_NAME>" "home" page
    [...]

    Examples:
      | site_name | hiptest-uid |
      | value1 |  |
      [...]
```

So as you can see, the examples table heading (`site_name`) is not going to match up with the variable reference in the scenario step (`<SITE_NAME>`) because the capitalization has been changed in one, but not both places.

To correct the problem, either no case conversion should take place, or the case conversion should be consistent for both data table headings and the references to them in steps.

**Comment by vincent-psarga** [comment]
Thank you for the feedback. I've committed some changes to hiptest-publisher that fixes this issue: https://github.com/hiptest/hiptest-publisher/commit/0905c1bc3f984559cae1e20b5ee84b24602e1d85

It's not released yet but should be soon and the SaaS version will follow shortly after :)
