### ISSUE TITLE
Share action words among projects

### ISSUE THREAD

**Issue by yael-lorenzo-olx** [hiptest/hiptest-issue-tracker#91]
I would like to share the same action words in different projects.

Currently we have iOs, Android and Web under the same project because we use many shared action words.

If we split them, we loose this capability.

**Comment by aurelien-reeves** [comment]
Hi,

As you can see on [our Trello backlog](https://trello.com/b/sSdBSlL0/cooking-up-for-the-coming-months), this is actually something that is work in progress.
