### ISSUE TITLE
not able to open the downloaded test run in excel

### ISSUE THREAD

**Issue by priyadarshinil** [hiptest/hiptest-issue-tracker#93]
### Steps to reproduce
1. create a test run
2. execute the test run
3. click download the test run

### Expected behaviour
able to open the downloaded xls test run

### Actual behaviour
not able to open the downloaded test run in excel, repair error is coming

### My configuration
**Browser:**
chrome
**Operating system:**
Mac OS

**Comment by aurelien-reeves** [comment]
Hi,

Could you please contact us at support@hiptest.net?
We may need to take a look at your excel file, and also maybe to your project.

What is your version of Excel?
