### ISSUE TITLE
Error message "Ember Data Request GET /projects/32796 returned a 400 Payload (Empty Content-Type)"

### ISSUE THREAD

**Issue by NatalijaRokina** [hiptest/hiptest-issue-tracker#95]
### Steps to reproduce
1.I navigate to https://hiptest.net/app/projects/32796/test-runs/138921/folder-snapshots/1038062
2. I see error message "Ember Data Request GET /projects/32796 returned a 400 Payload (Empty Content-Type)"
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
I see error message "Ember Data Request GET /projects/32796 returned a 400 Payload (Empty Content-Type)"

### My configuration
**Browser:** Chrome

**Operating system:** Windows10 version
<img width="934" alt="2018_03_09_15_11_53_https_hiptest net_app_projects_32796_test_runs_138921_folder_snapshots_1038062" src="https://user-images.githubusercontent.com/32734168/37209864-571578ae-23af-11e8-9080-041b6a3f7dc0.png">
1703

**Comment by aurelien-reeves** [comment]
Hi,

Does your session still opened?
Could you try navigating to https://hiptest.net/app/projects/ sign-in again if needed?

**Comment by cbliard** [comment]
It generally happens when you do not have access to a project. It's true that the message is scary.

Do you still experience issues?

**Comment by karamosky** [comment]
Hello @NatalijaRokina 
Do you still encounter this issue ?
I will close this one but feel free to reopen it if the problem still there.

**Comment by santhoshdharma** [comment]
I am facing the same issue. I tried incognito mode and different browser but no luck

Ember Data Request GET /projects/134367 returned a 400 Payload (Empty Content-Type)
![image](https://user-images.githubusercontent.com/41357584/62939582-442acd80-bdef-11e9-8479-4fffa83b5c0a.png)

**Comment by aurelien-reeves** [comment]
Hi @santhoshdharma 
Do you see the requested project in [app.hiptest.com/projects](https://app.hiptest.com/projects)?

**Comment by santhoshdharma** [comment]
I can see the projects when I click on https://app.hiptest.com/projects but getting the aforementioned error when I click on https://app.hiptest.com/projects/134367/test-runs

**Comment by aurelien-reeves** [comment]
This is due to missing permission to access the project 134367.
Check with your HipTest administrator to ask him access to the project with the ID 134367.
