### ISSUE TITLE
Add scenarios by folders to run

### ISSUE THREAD

**Issue by yastarshevsky** [hiptest/hiptest-issue-tracker#99]
I spend quite a lot of time adding scenarios to the run. Now it is not possible to add the entire folder. And we have cases when there are many subfolders in the folder and then adding scenarios to the run turns into hell.

**Comment by jracenet** [comment]
Hey @yastarshevsky,

We get your point and fully agree!
We will work on that ASAP and make possible adding all the scenarios of a folder in a test run at once.

Thank your for your feedback!

Joan

**Comment by HoudaDabou** [comment]
Hi @yastarshevsky,

Our team has developed this feature, feel free to discover it!

Regards,
Houda
